from rsf.proj import *
import math
from rsf.prog import RSFROOT
import sys
# sys.path.append('../barrolka/')
# import velcon3d

proj = Project()
prog = proj.Program('rtm3d.c')
prog2 = proj.Program('rtm3d2.c')

def Grey(data,other):
    Result(data,'''
    window |grey
    label1=Time unit1=s color=g label2=Distance unit2=km clip=0.3 wanttitle=n title= screenratio=1.0 
    %s ''' % (other))

def Grey3(data,clip,other):
    Result(data,'''
    window |byte clip=%g| grey3 flat=n frame1=100 frame2=20 frame3=20
    label1=Time unit1=s color=g label2=Inline unit2=km label3=Crossline unit3=km clip=0.3 wanttitle=y title= screenratio=1.0 point1=0.7 point2=0.6 label
    %s ''' % (clip,other))
 
def Greyi(data,clip,other):
    Result(data,'''
    threshold2 pclip=2|window |byte clip=%g | grey3 flat=n frame1=50 frame2=50 frame3=50
    label1=Time unit1=s color=g label2=Distance unit2=km clip=0.3 wanttitle=n title= screenratio=1.0 
    %s ''' % (clip,other))
    
def Greyii(data,datain,clip,other):
    Result(data,datain,'''
    threshold2 pclip=2|window |byte clip=%g | grey3 flat=n frame1=50 frame2=50 frame3=50
    label1=Time unit1=s color=g label2=Distance unit2=km clip=0.3 wanttitle=n title= screenratio=1.0 
    %s ''' % (clip,other))
    
## plot one image from the image sets
def Greyis(data,datain,i2,clip,other):
    Result(data,datain,'''
    threshold2 pclip=2|window n2=1 f2=%d|byte clip=%g | grey3 flat=n frame1=50 frame2=50 frame3=50
    label1=Time unit1=s color=g label2=Distance unit2=km clip=0.3 wanttitle=n title= screenratio=1.0 
    %s ''' % (i2,clip,other))
       
def Grey4(data,other):
    Result(data,'''
    window |byte clip=10| window max1=1.0| grey3 flat=n frame1=100 frame2=100 frame3=100
    label1=Time unit1=s color=g label2=Distance unit2=km clip=0.3 wanttitle=n title= screenratio=1.0 
    %s ''' % (other))

def Greyv(data,other):
    Result(data,'''
    window |byte allpos=y bias=1.0 clip=1.2 bar=bar.rsf| grey3 flat=n frame1=20 frame2=20 frame3=20
    label1=Time unit1=s color=g label2=Distance unit2=km clip=0.3 wanttitle=n title= screenratio=1.0 
    scalebar=y %s ''' % (other))
     
## The simplest 3D
Flow('r2',None,'spike n1=101 n2=101 n3=101 d1=0.01 d2=0.01 d3=0.01 o1=0 o2=0 o3=0| window n1=1 | math output=0.15')
Flow('a2','r2','math output=100|cut n1=50 | cut f1=51|cut n2=50 | cut f2=51')
# Flow('a2','r2','math output=100|cut n1=10 | cut f1=11|cut n2=10 | cut f2=11')

Flow('diffr2','r2 a2',
     '''
     	 kirmod3 nt=400 dt=0.002 freq=20 refl=${SOURCES[1]}
         nhx=1 h0x=0 dhx=0.05
         nhy=1 h0y=0 dhy=0.05 
         s0x=0 dsx=0.01 nsx=101 
         s0y=0 dsy=0.01 nsy=101 
         vel=2 gradz=1 type=v verb=n
     ''')
Grey3('diffr2',1,'')

Flow('diffr','diffr2','window|window n2=100 n3=100 n1=400')


## The more complicated 3D
#r3,a3: reflectors in 3D
Flow('r3',None,'spike n1=201 n2=201 n3=201 d1=0.01 d2=0.01 d3=0.01 o1=0 o2=0 o3=0| window n1=5 j1=10| math output="(0.5*x2+0.5*x3)*x1 + 0.2" | transp plane=12 | transp plane=23')
Result('r3-0','r3','window n3=1 f3=0|grey color=j title="First reflector" scalebar=y')
Result('r3-1','r3','window n3=1 f3=1|grey color=j title="First reflector" scalebar=y')
Result('r3-2','r3','window n3=1 f3=2|grey color=j title="Second reflector" scalebar=y')

Flow('a3','r3','math output=100|math output="input*(1-(x1-1)*(x1-1))*(1-(x2-1)*(x2-1))"')
Result('a3-0','a3','window n3=1 f3=0|grey pclip=100 title="First layer of diffractors" scalebar=y')
Result('a3-1','a3','window n3=1 f3=1|grey pclip=100 title="First layer of diffractors" scalebar=y')

## the following works
Flow('diffr3','r3 a3',
     '''
     	 kirmod3 nt=500 dt=0.004 freq=20 refl=${SOURCES[1]}
         nhx=1 h0x=0 dhx=0.05
         nhy=1 h0y=0 dhy=0.05 
         s0x=0 dsx=0.01 nsx=201 
         s0y=0 dsy=0.01 nsy=201 
         vel=2 gradz=1 type=v verb=n
     ''')


Flow('refl','diffr3','window|window j2=2 j3=2 | window n1=400|math output="input*0.4" | window n2=100 n3=100 n1=400')
Grey3('refl',1,'')
Grey3('diffr',1,'')

Flow('syn3d','diffr refl','add scale=1,1 ${SOURCES[1]}')
Grey3('syn3d',1,'')
     
########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun/'
matfun = 'Syn'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
    sys.stderr.write('\nCannot find Matlab.\n')
    sys.exit(1)

# n1=251
# n2=688
# n3=418
n1=400
n2=100
n3=100
d1=0.004
d2=0.05
d3=0.05
o1=0
o2=0
o3=0
lf=0
hf=100
verb=1

n1win=400
n2win=100
n3win=100

r1=0.5
r2=0.5
r3=0.5

put='n1=%d n2=%d n3=%d d1=%g d2=%g d3=%g o1=%g o2=%g o3=%g'%(n1,n2,n3,d1,d2,d3,o1,o2,o3)

N=200
N2=250
NN=3
ifdamp=0

#Local
## The simplest 3D
Flow('rr2',None,'spike n1=101 n2=101 n3=101 d1=0.01 d2=0.01 d3=0.01 o1=0 o2=0 o3=0| window n1=1 | math output=0.15')
Flow('aa2-1','rr2','math output=100|cut n2=20 | cut f2=21|cut n1=20 | cut f1=21')
Flow('aa2-2','rr2','math output=100|cut n2=20 | cut f2=21|cut n1=40 | cut f1=41')
Flow('aa2-3','rr2','math output=100|cut n2=20 | cut f2=21|cut n1=60 | cut f1=61')
Flow('aa2-4','rr2','math output=100|cut n2=20 | cut f2=21|cut n1=80 | cut f1=81')
Flow('aa2-11','rr2','math output=100|cut n2=40 | cut f2=41|cut n1=20 | cut f1=21')
Flow('aa2-22','rr2','math output=100|cut n2=40 | cut f2=41|cut n1=40 | cut f1=41')
Flow('aa2-33','rr2','math output=100|cut n2=40 | cut f2=41|cut n1=60 | cut f1=61')
Flow('aa2-44','rr2','math output=100|cut n2=40 | cut f2=41|cut n1=80 | cut f1=81')
Flow('aa2-111','rr2','math output=100|cut n2=60 | cut f2=61|cut n1=20 | cut f1=21')
Flow('aa2-222','rr2','math output=100|cut n2=60 | cut f2=61|cut n1=40 | cut f1=41')
Flow('aa2-333','rr2','math output=100|cut n2=60 | cut f2=61|cut n1=60 | cut f1=61')
Flow('aa2-444','rr2','math output=100|cut n2=60 | cut f2=61|cut n1=80 | cut f1=81')
Flow('aa2-1111','rr2','math output=100|cut n2=80 | cut f2=81|cut n1=20 | cut f1=21')
Flow('aa2-2222','rr2','math output=100|cut n2=80 | cut f2=81|cut n1=40 | cut f1=41')
Flow('aa2-3333','rr2','math output=100|cut n2=80 | cut f2=81|cut n1=60 | cut f1=61')
Flow('aa2-4444','rr2','math output=100|cut n2=80 | cut f2=81|cut n1=80 | cut f1=81')

Flow('aa2','aa2-1 aa2-2 aa2-3 aa2-4 aa2-11 aa2-22 aa2-33 aa2-44 aa2-111 aa2-222 aa2-333 aa2-444 aa2-1111 aa2-2222 aa2-3333 aa2-4444','add scale=1,1 ${SOURCES[1:16]}')

# Flow('a2','r2','math output=100|cut n1=10 | cut f1=11|cut n2=10 | cut f2=11')

Flow('diffr22','rr2 aa2',
     '''
     	 kirmod3 nt=400 dt=0.002 freq=80 refl=${SOURCES[1]}
         nhx=1 h0x=0 dhx=0.05
         nhy=1 h0y=0 dhy=0.05 
         s0x=0 dsx=0.01 nsx=101 
         s0y=0 dsy=0.01 nsy=101 
         vel=2 gradz=1 type=v verb=n
     ''')
Grey3('diffr22',1,'')

Flow('diffrr','diffr22','window|window n2=100 n3=100 n1=200 --out=stdout')
Flow('refll','refl','window|window n2=100 n3=100 n1=200 --out=stdout')
Flow('syn3d2','refll diffrr','add scale=1,1 ${SOURCES[1]} --out=stdout')
# Grey3('diffrr',2,'') 	## This is the correct version
# Grey3('refll',2,'') 	## This is the correct version
# Grey3('syn3d2',2,'')	## This is the correct version

### PWD
Flow('slope','syn3d2',
     '''
     dip rect1=20 rect2=20 rect3=20 order=2 verb=y
     ''')
#spray radii
ns2=2
ns3=2
Flow('s-pwd','syn3d2 slope',
     '''
     pwspray2 ns2=%d ns3=%d dip=${SOURCES[1]} order=2 verb=y eps=0.1|
     stack axis=2
     '''% (ns2,ns3))
Flow('s-pwd-nn','syn3d2 s-pwd','add scale=1,-1 ${SOURCES[1]}')
Flow('s-pwd-n','s-pwd-nn','cp')
# Grey3('s-pwd',2,'')
# Grey3('s-pwd-nn',2,'') ## This is the correct version

n1=200
n2=100
n3=100

n1win=200
n2win=40
n3win=40
# PWD: SNR=6.51808
# GRR: SNR=1.42052
# n1w=200, n2win=50, n3win=40, N=100, N2=125, LRR: SNR=1.28607, LRRA: SNR=1.84442
# n1w=200, n2win=50, n3win=40, N=80, N2=125, LRR: SNR=1.28607, LRRA: SNR=2.50694
# n1w=200, n2win=50, n3win=40, N=60, N2=125, LRR: SNR=1.28607, LRRA: SNR=3.50956
# n1w=200, n2win=50, n3win=40, N=30, N2=125, LRR: SNR=1.28607, LRRA: SNR=6.30337
# n1w=200, n2win=50, n3win=40, N=20, N2=125, LRR: SNR=1.28607, LRRA: SNR=7.61209
# n1w=200, n2win=50, n3win=40, N=18, N2=125, LRR: SNR=1.28607, LRRA: SNR=8.00433
# n1w=200, n2win=50, n3win=40, N=15, N2=125, LRR: SNR=1.28607, LRRA: SNR=8.60472
# n1w=200, n2win=50, n3win=40, N=14, N2=125, LRR: SNR=1.28607, LRRA: SNR=8.78414
# n1w=200, n2win=50, n3win=40, N=12, N2=125, LRR: SNR=1.28607, LRRA: SNR=8.88157
# n1w=200, n2win=50, n3win=40, N=11, N2=125, LRR: SNR=1.28607, LRRA: SNR=8.74348
# n1w=200, n2win=50, n3win=40, N=10, N2=125, LRR: SNR=1.28607, LRRA: SNR=8.09922
# n1w=200, n2win=50, n3win=40, N=9, N2=125, LRR: SNR=1.28607, LRRA: SNR=7.19439
# n1w=200, n2win=50, n3win=40, N=8, N2=125, LRR: SNR=1.28607, LRRA: SNR=5.70956
# n1w=200, n2win=50, n3win=40, N=5, N2=125, LRR: SNR=1.28607, LRRA: SNR=-2.96127

# n1w=200, n2win=50, n3win=40, N=12, N2=12, LRR: SNR=8.88403, LRRA: SNR=8.88403

# n1w=200, n2win=50, n3win=50, N=12, N2=12, LRR: SNR=8.31083, LRRA: SNR=8.31083

#Final results
# n1w=200, n2win=40, n3win=40, N=12, N2=12, LRRA: SNR=9.1435
# n1w=200, n2win=40, n3win=40, N=12, N2=100, LRRA: SNR=9.1435 (meaning that 12 is optimal)
# n1w=200, n2win=40, n3win=40, N=10, N2=100, LRRA: SNR=9.0596
# n1w=200, n2win=40, n3win=40, N=8, N2=100, LRRA: SNR=7.70044 
# n1w=200, n2win=40, n3win=40, N=3, N2=3, LRRA: SNR=-9.34767
# n1w=200, n2win=40, n3win=40, N=3, N2=50, LRRA: SNR=-3.11554

# n1w=200, n2win=20, n3win=20, N=12, N2=12, LRRA: SNR=2.8xxx
# n1w=200, n2win=20, n3win=20, N=6, N2=6, LRRA: SNR=6.18409
# n1w=200, n2win=20, n3win=20, N=3, N2=3, LRRA: SNR=5.43671 (demonstrating that adaptive strategy is better)
# n1w=200, n2win=20, n3win=20, N=3, N2=12, LRRA: SNR=5.75447 (demonstrating that adaptive strategy is better)
# n1w=200, n2win=20, n3win=20, N=2, N2=12, LRRA: SNR=1.72632 
# n1w=200, n2win=20, n3win=20, N=4, N2=12, LRRA: SNR=7.35554 (!!!)
# n1w=200, n2win=20, n3win=20, N=5, N2=12, LRRA: SNR=6.89074
# n1w=200, n2win=20, n3win=20, N=4, N2=4, LRRA: SNR=7.48538 


#nwin=100:  LRRA=1.42
#nwin=50:  LRRA=8.31
#nwin=40:  LRRA=9.14
#nwin=30:  LRRA=7.63 (N=10), 
#nwin=20:  LRRA=7.36
#nwin=16:  LRRA= 5.12 
#nwin=10:  LRRA=3.40 (N=2)

#GRR: N=60, SNR: 3.1426
#GRR: N=80, SNR: 2.12835
#GRR: N=120, SNR: 0.96421
#GRR: N=140, SNR: 0.652264

N=12
N2=50

NN=3
ifdamp=0
put='n1=%d n2=%d n3=%d d1=%g d2=%g d3=%g o1=%g o2=%g o3=%g'%(n1,n2,n3,d1,d2,d3,o1,o2,o3)


############################################################
## LRR
############################################################
Flow('s-lrr0 s-lrra0',[os.path.join(matROOT,matfun+'.m'),'s-pwd-nn','diffrr','refll'],
     '''MATLABPATH=%(matlabpath)s %(matlab)s 
     -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${SOURCES[1]}','${SOURCES[2]}','${SOURCES[3]}','${TARGETS[0]}','${TARGETS[1]}',%(n1)d,%(n2)d,%(n3)d,%(d1)g,%(lf)g,%(hf)g,%(N)d,%(N2)d,%(NN)d,%(n1win)d,%(n2win)d,%(n3win)d,%(r1)g,%(r2)g,%(r3)g,%(ifdamp)d,%(verb)d);quit"
     '''%vars(),stdin=0,stdout=-1)

Flow('s-lrr','s-lrr0','put %s'%put)
Flow('s-lrra','s-lrra0','put %s'%put)
Flow('s-lrr-n','syn3d2 s-lrr','add scale=1,-1 ${SOURCES[1]}')
Flow('s-lrra-n','syn3d2 s-lrra','add scale=1,-1 ${SOURCES[1]}')

############################################################
## GRR
############################################################
n1win=200
n2win=100
n3win=100
N=100
N2=100
Flow('s-grr0 s-grra0',[os.path.join(matROOT,matfun+'.m'),'s-pwd-nn','diffrr','refll'],
     '''MATLABPATH=%(matlabpath)s %(matlab)s 
     -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${SOURCES[1]}','${SOURCES[2]}','${SOURCES[3]}','${TARGETS[0]}','${TARGETS[1]}',%(n1)d,%(n2)d,%(n3)d,%(d1)g,%(lf)g,%(hf)g,%(N)d,%(N2)d,%(NN)d,%(n1win)d,%(n2win)d,%(n3win)d,%(r1)g,%(r2)g,%(r3)g,%(ifdamp)d,%(verb)d);quit"
     '''%vars(),stdin=0,stdout=-1)

Flow('s-grr','s-grr0','put %s'%put)
Flow('s-grra','s-grra0','put %s'%put)
Flow('s-grr-n','syn3d2 s-grr','add scale=1,-1 ${SOURCES[1]}')
Flow('s-grra-n','syn3d2 s-grra','add scale=1,-1 ${SOURCES[1]}')

# 
# n1win=200
# n2win=100
# n3win=100
# for i in range(4):
# 	sgrr0='s-grr0-%d'%i
# 	sgrra0='s-grra0-%d'%i
# 	sgrr='s-grr-%d'%i
# 	sgrra='s-grra-%d'%i
# 	sgrrn='s-grr-n-%d'%i
# 	sgrran='s-grra-n-%d'%i
# 	if(i<2):
# 	  N=60+i*20
# 	else:
# 	  N=80+i*20
# 	
# 	N2=N
# # 	Flow([sgrr0,sgrra0],[os.path.join(matROOT,matfun+'.m'),'s-pwd-nn','diffrr','refll'],
# #      '''MATLABPATH=%(matlabpath)s %(matlab)s 
# #      -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${SOURCES[1]}','${SOURCES[2]}','${SOURCES[3]}','${TARGETS[0]}','${TARGETS[1]}',%(n1)d,%(n2)d,%(n3)d,%(d1)g,%(lf)g,%(hf)g,%(N)d,%(N2)d,%(NN)d,%(n1win)d,%(n2win)d,%(n3win)d,%(r1)g,%(r2)g,%(r3)g,%(ifdamp)d,%(verb)d);quit"
# #      '''%vars(),stdin=0,stdout=-1)
# 	Flow(sgrr,sgrr0,'put %s'%put)
# 	Flow(sgrra,sgrra0,'put %s'%put)
# 	Flow(sgrrn,['syn3d2',sgrr],'add scale=1,-1 ${SOURCES[1]}')
# 	Flow(sgrran,['syn3d2',sgrra],'add scale=1,-1 ${SOURCES[1]}')
# 
# 	Grey3(sgrr,2,'')
# 	Grey3(sgrra,2,'')
# 	Grey3(sgrrn,2,'')
# 	Grey3(sgrran,2,'')
# 
# Result('comp',['Fig/s-grr-0.vpl','Fig/s-grr-1.vpl','Fig/s-grr-2.vpl','Fig/s-grr-3.vpl'],'SideBySideAniso')





Grey3('refll',2,'title=Reflections')
Grey3('diffrr',2,'title=Diffractions')
Grey3('syn3d2',2,'title="Synthetic data"')
 
Grey3('s-pwd',2,'title="PWD"')
Grey3('s-grr',2,'title="GRR"')
Grey3('s-lrr',2,'title="LRR"')
Grey3('s-lrra',2,'title="LRRA"')
Grey3('s-pwd-n',2,'title="PWD"')
Grey3('s-grr-n',2,'title="GRR"') 
Grey3('s-lrr-n',2,'title="LRR"')
Grey3('s-lrra-n',2,'title="LRRA"')  

Flow('s-pwd-e','diffrr s-pwd-n','add scale=1,-1 ${SOURCES[1]}')
Flow('s-grr-e','diffrr s-grr-n','add scale=1,-1 ${SOURCES[1]}')
Flow('s-lrr-e','diffrr s-lrr-n','add scale=1,-1 ${SOURCES[1]}')
Flow('s-lrra-e','diffrr s-lrra-n','add scale=1,-1 ${SOURCES[1]}')

Grey3('s-pwd-e',2,'title="PWD"') 
Grey3('s-grr-e',2,'title="GRR"') 
Grey3('s-lrr-e',2,'title="LRR"')
Grey3('s-lrra-e',2,'title="LRRA"')  

#add label
Plot('ls1',None,
	'''
	box x0=2 y0=3.8 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('ls2',None,
	'''
	box x0=3 y0=3.2 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('ls3',None,
	'''
	box x0=4 y0=2.6 label="" xt=0.5 yt=0.5 length=0.5 
	''')

Plot('ls4',None,
	'''
	box x0=2.6 y0=4.6 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('ls5',None,
	'''
	box x0=3.6 y0=4.6 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('ls6',None,
	'''
	box x0=4.6 y0=4.6 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('ls7',None,
	'''
	box x0=4.6 y0=5.3 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('ls8',None,
	'''
	box x0=1.8 y0=4.6 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Result('s-pwd-0','Fig/s-pwd.vpl ls1 ls2 ls3','Overlay')
Result('s-grr-0','Fig/s-grr.vpl ls1 ls2 ls3','Overlay')
Result('s-lrra-0','Fig/s-lrra.vpl ls1 ls2 ls3','Overlay')

Result('s-pwd-n-0','Fig/s-pwd-n.vpl ls4 ls5 ls6 ls7 ls8','Overlay')
Result('s-grr-n-0','Fig/s-grr-n.vpl ls4 ls5 ls6 ls7 ls8','Overlay')
Result('s-lrra-n-0','Fig/s-lrra-n.vpl ls4 ls5 ls6 ls7 ls8','Overlay')

Result('s-pwd-e-0','Fig/s-pwd-e.vpl ls4 ls5 ls6 ls7 ls8','Overlay')
Result('s-grr-e-0','Fig/s-grr-e.vpl ls4 ls5 ls6 ls7 ls8','Overlay')
Result('s-lrr-e-0','Fig/s-lrr-e.vpl ls4 ls5 ls6 ls7 ls8','Overlay')
Result('s-lrra-e-0','Fig/s-lrra-e.vpl ls4 ls5 ls6 ls7 ls8','Overlay')



End()
