from rsf.proj import *
import os
sys.path.append('../hyper/')
from radius2 import radius2

#/Volumes/CHENYK2/SeismicDataYangkang/Real/guochangfx/

from math import *
def Grey(data,other): 
	Result(data,'grey label2=Trace unit2="" label1=Time unit1="s" title="" wherexlabel=b wheretitle=t scalebar=n  clip=2  %s  '%other)

def Greyr(data,data1,other): 
	Result(data,data1,'grey label2=Trace unit2="" label1=Time unit1="s" title="" wherexlabel=b wheretitle=t scalebar=n mean=y scalebar=y barlabel=Radius barunit=samples  %s  '%other)

def Greydemo(datao,datai,other): 
	Plot(datao,datai,'grey label2=Trace unit2="" label1=Time unit1="s" title="" wherexlabel=t wheretitle=b scalebar=n  clip=2  %s  '%other)

def Greynoise(data,other): 
	Result(data,'grey label2=Trace unit2="" label1=Time unit1="s" title="" wherexlabel=b wheretitle=t scalebar=n color=j  minval=-0.4 maxval=0.4 clip=0.2 %s  '%other)

#----------------------------------------------dat


Flow('g',os.getenv('HOME')+'/chenyk.data4/gc/gc2.bin','dd form=native | put d2=1')

# Flow('g','image2d','dd form=native')
Flow('mask','g','envelope | causint | math output="input*input" | mask min=40 | dd type=float')

########## Patch
Flow('patch','g','patch w=256,1001 p=20,1')
Flow('patch0','patch','patch inv=y weight=y dim=2')

#Result('patch','patch','grey title="Patch Data"')
#Result('patch0','patch0','grey title=" Inv Patch Data"')
nx=1001
nshifts = []
for s in range(1,5):

    nshift = 'nshifg-%d' % s
    Flow(nshift,'patch','window f2=%d | pad end2=%d' % (s,s))
    nshifts.append(nshift)

    nshift = 'nshift+%d' % s
    Flow(nshift,'patch','window n2=%d | pad beg2=%d ' % (nx-s,s)) 
    nshifts.append(nshift)


Flow('nshifts',nshifts,'cat ${SOURCES[1:%d]} axis=4 | put o2=0 ' % len(nshifts))

wflts = []
wpres = []
for nwt in range(0,20):
    wdata  = 'wdata%d'  % nwt
    wshift = 'wshift%d' % nwt
    wflt   = 'wfl%d'    % nwt
    wpre   = 'wpre%d'    % nwt
    Flow(wdata,'patch','window n3=1 f3=%d | fft1 ' % nwt) 
    Flow(wshift,'nshifts','window n3=1 f3=%d | window | fft1' % nwt)   
    Flow([wflt, wpre],[wshift, wdata],
         'clpf match=${SOURCES[1]} pred=${TARGETS[1]} rect2=20 rect1=3 niter=10 verb=n')
    wpres.append(wpre)

Flow('pre',wpres,'cat ${SOURCES[1:%d]} axis=4 | fft1 inv=y  ' % len(wpres))
Flow('g-rna','pre','transp plane=34 memsize=1000 | patch inv=y weight=y dim=2 --out=stdout')
Flow('g-rna-n','g g-rna','add scale=1,-1 ${SOURCES[1]} --out=stdout')

# ortho
Flow('g-ortho-n g-ortho','g-rna-n g-rna','ortho niter=100 rect1=3 rect2=3 sig=${SOURCES[1]} sig2=${TARGETS[1]}')


# non-stationary ortho
Flow('g-high','g','cp')
Flow('g-low','g','bandpass fhi=25')
#Flow('g-low','g-fx','cp')
Grey('g-high','')
Grey('g-low','')

# Flow('g-high','g-fx','cp | noise var=0.05 seed=202021')
# Flow('g-low','g-high','bandpass fhi=20')
# Grey('g-high','')
# Grey('g-low','')
#sfpen Fig/high-smooth-spec00.vpl Fig/high-smooth-spec10.vpl Fig/high-smooth-spec20.vpl Fig/high-smooth-spec30.vpl Fig/high-smooth-spec40.vpl Fig/high-smooth-spec50.vpl

radius2('g-high','g-low', 
                niter=5, 
#                 c=[0.7,0.45,0.35,0.35,0.5], #works fine
                c=[0.7,0.4,0.2,0.1,0.05], #works fine
                bias=-20, clip=30, 
                rect1=30, rect2=20, 
                theor=False, initial=1, 
                minval=-20, maxval=20, 
                titlehigh='High', titlelow='Low',
                it=0 )
                
Flow('rect1','rect50','math output="input+0.1"')
Flow('rect2','rect50','math output="input+0.1"')


Greyr('g-rect10','rect10','color=j scalebar=y')
Greyr('g-rect20','rect20','color=j scalebar=y')
Greyr('g-rect30','rect30','color=j scalebar=y')
Greyr('g-rect40','rect40','color=j scalebar=y')
Greyr('g-rect50','rect50','color=j scalebar=y')


Flow('g-orthon-n g-orthon','g-rna-n g-rna rect1 rect2','orthon niter=100 sig=${SOURCES[1]} sig2=${TARGETS[1]} rect1=${SOURCES[2]} rect2=${SOURCES[3]} eps=0.00')


Flow('g-rna-s','g-rna g-rna-n','similarity other=${SOURCES[1]} niter=40 rect1=5 rect2=5')
Flow('g-ortho-s','g-ortho g-ortho-n','similarity other=${SOURCES[1]} niter=40 rect1=5 rect2=5')
Flow('g-orthon-s','g-orthon g-orthon-n','similarity other=${SOURCES[1]} niter=40 rect1=5 rect2=5')

Grey('g','')
Grey('g-rna',' ')
Grey('g-rna-n',' ')
Grey('g-ortho',' ')
Grey('g-ortho-n','')
Grey('g-orthon',' ')
Grey('g-orthon-n','')





## Creating framebox
x1=5
y1=3
wx1=200
wy1=1.5

Flow('frame1.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	string.join(map(str,(x1,y1,x1+wx1,y1,x1+wx1,y1+wy1,x1,y1+wy1,x1,y1))))
Plot('frame1','frame1.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=1000 min2=1 max2=6 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n
	''')

## Creating framebox
x2=350
y2=3.7
wx2=200
wy2=1.0

Flow('frame2.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	string.join(map(str,(x2,y2,x2+wx2,y2,x2+wx2,y2+wy2,x2,y2+wy2,x2,y2))))
Plot('frame2','frame2.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=1000 min2=1 max2=6 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n
	''')

Plot('label1',None,
	'''
	box x0=4.5 y0=5.9 label="A" xt=0.5 yt=0.5 length=0.75 
	''')

## Create label B
Plot('label2',None,
	'''
	box x0=7.4 y0=4.95 label="B" xt=0.5 yt=0.5 length=0.75 
	''')
	
## Create label A
Plot('labela',None,
	'''
	box x0=5.5 y0=5.9 label="A" xt=0.5 yt=0.5 length=0.75 
	''')

## Create label B
Plot('labelb',None,
	'''
	box x0=8.9 y0=5.3 label="B" xt=0.5 yt=0.5 length=0.75 
	''')
	
## Create label C
Plot('labelc',None,
	'''
	box x0=7.3 y0=6.6 label="Missing" xt=0.5 yt=0.5 length=0.75 
	''')
Plot('labelcc',None,
	'''
	box x0=7.3 y0=6.6 label="Filled" xt=0.5 yt=0.5 length=0.75 
	''')
## Create label D
Plot('labeld',None,
	'''
	box x0=10.8 y0=6.0 label="Missing" xt=0.5 yt=0.5 length=0.75 
	''')
Plot('labeldd',None,
	'''
	box x0=10.8 y0=6.0 label="Filled" xt=0.5 yt=0.5 length=0.75 
	''')
## Create label E
Plot('labele',None,
	'''
	box x0=4.5 y0=7.5 label="Missing" xt=0.5 yt=0.5 length=0.75 
	''')
Plot('labelee',None,
	'''
	box x0=4.5 y0=7.5 label="Filled" xt=0.5 yt=0.5 length=0.75 
	''')
## Create label F
Plot('labelf',None,
	'''
	box x0=10.8 y0=6.0 label="Missing" xt=0.5 yt=0.5 length=0.75 
	''')
Plot('labelff',None,
	'''
	box x0=10.8 y0=6.0 label="Filled" xt=0.5 yt=0.5 length=0.75 
	''')
			
# Result('g-0','Fig/g.vpl frame1 frame2 labela labelb','Overlay')
# Result('g-orthon-0','Fig/g-orthon.vpl frame1 frame2 labela labelb','Overlay')
# Result('g-ortho-0','Fig/g-ortho.vpl frame1 frame2 labela labelb','Overlay')
# Result('g-rna-0','Fig/g-rna.vpl frame1 frame2 labela labelb','Overlay')	
# Result('g-orthon-n0','Fig/g-orthon-n.vpl frame1 frame2 labela labelb','Overlay')
# Result('g-ortho-n0','Fig/g-ortho-n.vpl frame1 frame2 labela labelb','Overlay')
# Result('g-rna-n0','Fig/g-rna-n.vpl frame1 frame2 labela labelb','Overlay')
# 
# 
# Grey('g-rna-s','color=j clip=0.4 scalebar=y minval=0 maxval=0.5')
# Grey('g-ortho-s','color=j clip=0.4 scalebar=y minval=0 maxval=0.5')
# Grey('g-orthon-s','color=j clip=0.4 scalebar=y minval=0 maxval=0.5')
# 
# Flow('g-z-a','g',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-z-b','g',' window n1=400 f1=1200 n2=200 f2=450 ')
# Flow('g-rna-z-a','g-rna',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-rna-z-b','g-rna',' window n1=400 f1=1200 n2=200 f2=450 ')
# Flow('g-ortho-z-a','g-ortho',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-ortho-z-b','g-ortho',' window n1=400 f1=1200 n2=200 f2=450')
# Flow('g-orthon-z-a','g-orthon',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-orthon-z-b','g-orthon',' window n1=400 f1=1200 n2=200 f2=450')
# Grey('g-z-a','')
# Grey('g-z-b','')
# Grey('g-rna-z-a','')
# Grey('g-rna-z-b','')
# Grey('g-ortho-z-a','')
# Grey('g-ortho-z-b','')
# Grey('g-orthon-z-a','')
# Grey('g-orthon-z-b','')
# 
# Result('g-rna-z-a0','Fig/g-rna-z-a.vpl labelc labeld','Overlay')
# Result('g-ortho-z-a0','Fig/g-ortho-z-a.vpl labelc labeld','Overlay')
# Result('g-orthon-z-a0','Fig/g-orthon-z-a.vpl labelcc labeldd','Overlay')
# 
# Result('g-rna-z-b0','Fig/g-rna-z-b.vpl labele labelf','Overlay')
# Result('g-ortho-z-b0','Fig/g-ortho-z-b.vpl labele labelf','Overlay')
# Result('g-orthon-z-b0','Fig/g-orthon-z-b.vpl labelee labelff','Overlay')
# 
# 
# Flow('g-rna-n-z-a','g-rna-n',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-rna-n-z-b','g-rna-n',' window n1=400 f1=1200 n2=200 f2=450 ')
# Flow('g-ortho-n-z-a','g-ortho-n',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-ortho-n-z-b','g-ortho-n',' window n1=400 f1=1200 n2=200 f2=450')
# Flow('g-orthon-n-z-a','g-orthon-n',' window n1=400 f1=1000 n2=175 f2=225')
# Flow('g-orthon-n-z-b','g-orthon-n',' window n1=400 f1=1200 n2=200 f2=450')
# 
# Grey('g-rna-n-z-a','')
# Grey('g-rna-n-z-b','')
# Grey('g-ortho-n-z-a','')
# Grey('g-ortho-n-z-b','')
# Grey('g-orthon-n-z-a','')
# Grey('g-orthon-n-z-b','')

#sfpen Fig/g-rna-n-z-a.vpl Fig/g-ortho-n-z-a.vpl Fig/g-orthon-n-z-a.vpl
#sfpen Fig/g-rna-n-z-b.vpl Fig/g-ortho-n-z-b.vpl Fig/g-orthon-n-z-b.vpl

Greydemo('a','g','title="Noisy data" labelsz=10 labelfat=4')
Greydemo('b','g-ortho','title="Denoised data" labelsz=10 labelfat=4')
Greydemo('c','g-ortho-n','title="Removed noise" labelsz=10 labelfat=4' )
Greydemo('d','g-ortho-s','color=j clip=0.5 scalebar=y minval=0 maxval=0.5 title="Local similarity between denoised data and removed noise" labelsz=10 labelfat=4')

Plot('data1','a b','SideBySideAniso')
Plot('data2','c d','SideBySideAniso')
Result('demon','data1 data2','OverUnderAniso')


## FOLLOWING NONSTATIONARY ORTHO
Flow('g-dip1','g','dip rect1=8 rect2=8 order=2 ')
Flow('g-dip2','g','dip rect1=100 rect2=100 order=2 ')

Grey('g-dip1','color=j clip=2 scalebar=y')
Grey('g-dip2','color=j clip=2 scalebar=y')

### non-stationary dip estimation
Flow('rect1-nn','g','scale axis=2 | math output="abs(input)" |mask min=0.0001 | dd type=float  |math output="30-input*25"')
Flow('rect2-nn','g','scale axis=2 | math output="abs(input)" |mask min=0.0001 | dd type=float  |math output="30-input*25"')
Greyr('rect1-nn','rect1-nn','color=j scalebar=y')
Greyr('rect2-nn','rect2-nn','color=j scalebar=y')

Flow('rectdip1','rect1','math output="(input)*4"')
Flow('rectdip2','rect2','math output="(input)*4"')
Greyr('g-rectdip1','rectdip1','color=j scalebar=y')
Greyr('g-rectdip2','rectdip2','color=j scalebar=y')

# Flow('rectdip1','rect1-n','math output="input"')
# Flow('rectdip2','rect2-n','math output="input"')

Flow('g-dip3','g rectdip1 rectdip2','dipn rect1=${SOURCES[1]} rect2=${SOURCES[2]} order=2 verb=y')
Grey('g-dip3','color=j clip=2 scalebar=y')


Flow('g-sm1','g g-dip1','pwsmooth dip=${SOURCES[1]} eps=0.1 ns=5 order=2')
Flow('g-sm2','g g-dip2','pwsmooth dip=${SOURCES[1]} eps=0.1 ns=5 order=2')
Flow('g-sm3','g g-dip3','pwsmooth dip=${SOURCES[1]} eps=0.1 ns=5 order=2')

Flow('g-sm1-n','g g-sm1','add scale=1,-1 ${SOURCES[1]} ')
Flow('g-sm2-n','g g-sm2','add scale=1,-1 ${SOURCES[1]} ')
Flow('g-sm3-n','g g-sm3','add scale=1,-1 ${SOURCES[1]} ')

Grey('g','clip=0.8')
Grey('g-sm1','clip=0.8')
Grey('g-sm2','clip=0.8')
Grey('g-sm3','clip=0.8')

Grey('g-sm1-n','clip=0.8')
Grey('g-sm2-n','clip=0.8')
Grey('g-sm3-n','clip=0.8')

Result('g-0','Fig/g.vpl frame1 frame2 label1 label2','Overlay')
Result('g-sm1-0','Fig/g-sm1.vpl frame1 frame2 label1 label2','Overlay')
Result('g-sm2-0','Fig/g-sm2.vpl frame1 frame2 label1 label2','Overlay')
Result('g-sm3-0','Fig/g-sm3.vpl frame1 frame2 label1 label2','Overlay')


###
Flow('g-z-a','g',' window min1=%g max1=%g min2=%g max2=%g'%(y1,y1+wy1,x1,x1+wx1))
Flow('g-z-b','g',' window min1=%g max1=%g min2=%g max2=%g'%(y2,y2+wy2,x2,x2+wx2))
Flow('g-sm1-z-a','g-sm1','window min1=%g max1=%g min2=%g max2=%g'%(y1,y1+wy1,x1,x1+wx1))
Flow('g-sm1-z-b','g-sm1','window min1=%g max1=%g min2=%g max2=%g'%(y2,y2+wy2,x2,x2+wx2))
Flow('g-sm2-z-a','g-sm2','window min1=%g max1=%g min2=%g max2=%g'%(y1,y1+wy1,x1,x1+wx1))
Flow('g-sm2-z-b','g-sm2','window min1=%g max1=%g min2=%g max2=%g'%(y2,y2+wy2,x2,x2+wx2))
Flow('g-sm3-z-a','g-sm3','window min1=%g max1=%g min2=%g max2=%g'%(y1,y1+wy1,x1,x1+wx1))
Flow('g-sm3-z-b','g-sm3','window min1=%g max1=%g min2=%g max2=%g'%(y2,y2+wy2,x2,x2+wx2))
Grey('g-z-a','clip=0.8')
Grey('g-z-b','clip=0.8')
Grey('g-sm1-z-a','clip=0.8')
Grey('g-sm2-z-a','clip=0.8')
Grey('g-sm3-z-a','clip=0.8')
Grey('g-sm1-z-b','clip=0.8')
Grey('g-sm2-z-b','clip=0.8')
Grey('g-sm3-z-b','clip=0.8')

Plot('labela1',None,
	'''
	box x0=8.1 y0=3.6 label="" xt=0.5 yt=0.5 length=0.75 
	''')
Plot('labela2',None,
	'''
	box x0=5.1 y0=3.6 label="" xt=-0.5 yt=0.5 length=0.75 
	''')
Plot('labela3',None,
	'''
	box x0=9.1 y0=2.6 label="" xt=0.5 yt=0.5 length=0.75 
	''')
	
Plot('labelb1',None,
	'''
	box x0=5.1 y0=5.6 label="" xt=-0.5 yt=0.5 length=0.75 
	''')
Plot('labelb2',None,
	'''
	box x0=5.1 y0=4.6 label="" xt=-0.5 yt=0.5 length=0.75 
	''')
Plot('labelb3',None,
	'''
	box x0=5.1 y0=3.6 label="" xt=-0.5 yt=0.5 length=0.75 
	''')
Result('g-sm1-z-a0','Fig/g-sm1-z-a.vpl labela1 labela2 labela3','Overlay')
Result('g-sm2-z-a0','Fig/g-sm2-z-a.vpl labela1 labela2 labela3','Overlay')
Result('g-sm3-z-a0','Fig/g-sm3-z-a.vpl labela1 labela2 labela3','Overlay')

Result('g-sm1-z-b0','Fig/g-sm1-z-b.vpl labelb1 labelb2 labelb3','Overlay')
Result('g-sm2-z-b0','Fig/g-sm2-z-b.vpl labelb1 labelb2 labelb3','Overlay')
Result('g-sm3-z-b0','Fig/g-sm3-z-b.vpl labelb1 labelb2 labelb3','Overlay')

End()
