from rsf.proj import*
from rsf.prog import RSFROOT
from math import pi

# data place:
# /media/CHENYK2/SeismicDataYangkang/drr5d/data/

# Data size: 101*32*32*5*5

def Grey3(data,other):
	Result(data,
       '''
       byte clip=0.4 |
       grey3 flat=n frame1=40 frame2=2 frame3=5 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title=
       screenratio=1.6 color=b font=104 %s'''%other)

def Grey(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.6 title=
       screenratio=0.2 color=b max1=0.4 font=104 %s'''%other)

def Greys(data,other):
	Result(data,
       '''
       grey gainpanel=all allpos=y label2=Trace label1="Time" unit1=s clip=1.2 title=
       screenratio=0.3 color=j max1=0.4 scalebar=y %s minval=0 maxval=1.2 font=104'''%other)

def Grey3e(data,other,clip):
	Result(data,
       '''
       byte clip=%g |
       grey3 flat=n frame1=40 frame2=2 frame3=5 
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s title=
       screenratio=1.4 color=b font=104 %s'''%(clip,other))


## Load data
########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'hyper'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

############################################################
## generate and process synthetic data
############################################################
Flow('hyper-clean-0 hyper-noisy-0 hyper-obs-0 hyper-drr-0 hyper-hooi-0 hyper-mrc-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}','${TARGETS[5]}');quit"
    '''%vars(),stdin=0,stdout=-1)
    
Flow('hyper-clean','hyper-clean-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-noisy','hyper-noisy-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-obs','hyper-obs-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-drr','hyper-drr-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-hooi','hyper-hooi-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-mrc','hyper-mrc-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')

Flow('hyper-clean2d','hyper-clean','window n4=1 n5=1 f4=3 f5=3| put n2=500 n3=1')
Flow('hyper-noisy2d','hyper-noisy','window n4=1 n5=1 f4=3 f5=3| put n2=500 n3=1')
Flow('hyper-obs2d','hyper-obs','window n4=1 n5=1 f4=3 f5=3| put n2=500 n3=1')
Flow('hyper-drr2d','hyper-drr','window n4=1 n5=1 f4=3 f5=3| put n2=500 n3=1')
Flow('hyper-hooi2d','hyper-hooi','window n4=1 n5=1 f4=3 f5=3| put n2=500 n3=1')
Flow('hyper-mrc2d','hyper-mrc','window n4=1 n5=1 f4=3 f5=3| put n2=500 n3=1')

Grey('hyper-clean2d','title=Clean')
Grey('hyper-noisy2d','title=Noisy')
Grey('hyper-obs2d','title=Observed')
Grey('hyper-hooi2d','title=HOOI')
Grey('hyper-drr2d','title=DRR')
Grey('hyper-mrc2d','title=Proposed')

Flow('hyper-drr2de','hyper-clean2d hyper-drr2d','add scale=1,-1 ${SOURCES[1]}')
Flow('hyper-hooi2de','hyper-clean2d hyper-hooi2d','add scale=1,-1 ${SOURCES[1]}')
Flow('hyper-mrc2de','hyper-clean2d hyper-mrc2d','add scale=1,-1 ${SOURCES[1]}')

Flow('hyper-drr2d-e','hyper-drr2de','window f2=190 n2=112 min1=0.0 max2=0.15')
Flow('hyper-hooi2d-e','hyper-hooi2de','window f2=190 n2=112 min1=0.0 max2=0.15')
Flow('hyper-mrc2d-e','hyper-mrc2de','window f2=190 n2=112 min1=0.0 max2=0.15')

Grey('hyper-hooi2d-e','title=HOOI screenratio=1')
Grey('hyper-drr2d-e','title=DRR screenratio=1')
Grey('hyper-mrc2d-e','title=Proposed screenratio=1')

Flow('hyper-z-clean','hyper-clean2d','window f2=190 n2=112 min1=0.0 max2=0.15')
Flow('hyper-z-obs','hyper-obs2d','window f2=190 n2=112 min1=0.0 max2=0.15')
Flow('hyper-z-hooi','hyper-hooi2d','window f2=190 n2=112 min1=0.0 max2=0.15')
Flow('hyper-z-drr','hyper-drr2d','window f2=190 n2=112 min1=0.0 max2=0.15')
Flow('hyper-z-mrc','hyper-mrc2d','window f2=190 n2=112 min1=0.0 max2=0.15')
Grey('hyper-z-clean','title=Clean screenratio=1')
Grey('hyper-z-obs','title=Observed screenratio=1')
Grey('hyper-z-drr','title=DRR screenratio=1')
Grey('hyper-z-hooi','title=HOOI screenratio=1')
Grey('hyper-z-mrc','title=Proposed screenratio=1')

## Creating framebox
x=390
y=0.0
w=230
w1=0.4

Flow('frame.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(x,y,x+w,y,x+w,y+w1,x,y+w1,x,y))))
Plot('frame','frame.asc',
	'''
	dd type=complex form=native |
	graph min1=1 max1=1024 min2=0 max2=0.4 pad=n plotfat=15 plotcol=6 screenratio=0.2
	wantaxis=n wanttitle=n yreverse=y 
	''')

Result('hyper-clean2d-0','Fig/hyper-clean2d.vpl frame','Overlay')	
Result('hyper-obs2d-0','Fig/hyper-obs2d.vpl frame','Overlay')
Result('hyper-drr2d-0','Fig/hyper-drr2d.vpl frame','Overlay')
Result('hyper-hooi2d-0','Fig/hyper-hooi2d.vpl frame','Overlay')
Result('hyper-mrc2d-0','Fig/hyper-mrc2d.vpl frame','Overlay')

End()
