from rsf.proj import *
from rsf.prog import RSFROOT
from math import pi
#from rsf.recipes.beg import server as private



def Grey(data,other):
	Result(data,
	'''
    window n4=1 n5=1 f4=15 f5=7  | 
    byte allpos=n clip=0.5 |
    grey3 title=  label2=X label3=Y label1="Time" unit1=s 
    point1=0.8 point2=0.8 frame1=50 frame2=3 frame3=5
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=1.3
    font=2 labelfat=2 titlefat=2 %s
    '''%other)

def Grey11(data,other):
	Result(data,
	'''
    window n4=1 n5=1 f4=10 f5=10  | 
    byte allpos=n clip=0.5 |
    grey3 title=  label2=X label3=Y label1="Time" unit1=s 
    point1=0.8 point2=0.8 frame1=50 frame2=6 frame3=10
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=1.3
    font=2 labelfat=2 titlefat=2 %s
    '''%other)

def Greym(data,other):
	Result(data,
	'''
    n4=1 n5=1 f4=15 f5=7  | 
    byte allpos=n clip=1.1 bar=bar.rsf |
    grey3 title=  label2=X label3=Y label1="Time" unit1=s 
    point1=0.8 point2=0.8 frame1=50 frame2=5 frame3=5
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=1.3
    font=2 labelfat=2 titlefat=2 scalebar=y %s
    '''%other)

def Grey2(data,data0,other):
	Result(data,data0,
	'''
    window n2=1 f2=5 n3=1 f3=5 | 
    byte allpos=n clip=0.5 |
    grey3 title=  label2=Hx label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=3 frame3=5
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=1.3
    font=2 labelfat=2 titlefat=2 %s
    '''%other)   

def Grey22(data,data0,other):
	Result(data,data0,
	'''
    window n2=1 f2=10 n3=1 f3=10 | 
    byte allpos=n clip=0.5 |
    grey3 title=  label2=Hx label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=6 frame3=10
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=1.3
    font=2 labelfat=2 titlefat=2 %s
    '''%other)   

def Grey3(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=15 f5=7 | put n2=100 n3=1 |
    grey title=  label2=Trace label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=3 frame3=5
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=0.3
    font=2 labelfat=2 titlefat=2 clip=0.3 %s
    '''%other) 

def Grey33(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=10 f5=10 | put n2=400 n3=1 |
    grey title=  label2=Trace label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=6 frame3=10
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=0.3
    font=2 labelfat=2 titlefat=2 clip=0.3 %s
    '''%other) 

def Grey33fk(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=10 f5=10 | fft1 | fft3 axis=2 |fft3 axis=3 |cabs|put n2=400 n3=1 o2=1 d2=1|window max1=80| scale axis=2|
    grey title=  label2="Wavenumber Trace" label3=Hy label1="Frequency" unit1=Hz 
    point1=0.8 point2=0.7 frame1=50 frame2=6 frame3=10
    parallel2=n  screenratio=0.3
    font=2 labelfat=2 titlefat=2 clip=10 allpos=y color=j %s
    '''%other) 
    
def Grey4(data,data0,other):
	Result(data,data0,
	'''
    window n2=1 f2=5 n3=1 f3=5 | put n2=210 n3=1 |
    grey title=  label2=Trace label3=Y label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=3 frame3=5
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=0.3
    font=2 labelfat=2 titlefat=2 clip=0.3 %s
    '''%other)   

def Grey44(data,data0,other):
	Result(data,data0,
	'''
    window n2=1 f2=10 n3=1 f3=10 | put n2=420 n3=1 |
    grey title=  label2=Trace label3=Y label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=6 frame3=10
    parallel2=n o2num=0 d2num=0.1 n2tic=10 screenratio=0.3
    font=2 labelfat=2 titlefat=2 clip=0.3 %s
    '''%other) 

def Greyz(data,other):
	Result(data,
	'''
    grey title=  label2=Trace label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=3 frame3=5
    parallel2=n screenratio=0.5 n2tic=5
    font=2 labelfat=2 titlefat=2 clip=0.5 %s
    '''%other) 
########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'Real5d'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

put="n1=250 o1=0 d1=0.004 n2=10 n3=10 n4=21 n5=10 o2=1 d2=1 o3=1 d3=1 o4=1 d4=1 o5=1 d5=1"
put2="n1=250 o1=0 d1=0.004 n2=20 n3=20 n4=42 n5=20 o2=1 d2=1 o3=1 d3=1 o4=1 d4=1 o5=1 d5=1"
############################################################
## generate and process synthetic data
############################################################   
Flow('r_obs5d-0 r_mask5d-0 r_drr5d-0 r_obs5d2-0 r_mask5d2-0 r_mask5d2t-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}','${TARGETS[5]}');quit"
    '''%vars(),stdin=0,stdout=-1)
    
    
Flow('r_obs5d','r_obs5d-0',' put %s | scale axis=5'%put)
Flow('r_mask5d','r_mask5d-0',' put %s '%put)
Flow('r_drr5d','r_drr5d-0',' put %s '%put)

## Dealiased
Flow('r_obs5d_new','r_obs5d2-0','put %s | window j4=2'%put2)
Flow('r_mask5d_new','r_mask5d2-0','put %s | window j4=2'%put2)

# 5D APEF
Flow('r_apef5 r_mask5d2','r_obs5d r_mask5d',
     '''
     npef5 maskin=${SOURCES[1]} maskout=${TARGETS[1]} jump=1
     a=4,2,2,1,1 niter=100 rect1=20 rect2=5 rect3=5 rect4=5 rect5=5 verb=y 
     ''')
     
Flow('r_recon5d','r_obs5d r_apef5 r_mask5d',
     '''
     npef5_recon filt=${SOURCES[1]} mask=${SOURCES[2]} niter=100 verb=y  
     ''')

Grey('r_obs5d','')
Grey('r_recon5d','')
Grey('r_drr5d','')

Grey2('r_obs5d-2','r_obs5d','')
Grey2('r_recon5d-2','r_recon5d','')
Grey2('r_drr5d-2','r_drr5d','')

Grey3('r_obs5d-3','r_obs5d','clip=0.4')#original data has some large-amplitude noise
Grey3('r_recon5d-3','r_recon5d','clip=0.4')
Grey3('r_drr5d-3','r_drr5d','clip=0.4')

Grey4('r_obs5d-4','r_obs5d','clip=0.4')
Grey4('r_recon5d-4','r_recon5d','clip=0.4')
Grey4('r_drr5d-4','r_drr5d','clip=0.4')


## zooming
#framebox A
x=10
y=0.2
w=20
w1=0.2

Flow('frameA.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(x,y,x+w,y,x+w,y+w1,x,y+w1,x,y))))
Plot('frameA','frameA.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=100 min2=0 max2=1 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n screenratio=0.3
	''')
#label A
Plot('labelA',None,
	'''
	box x0=11.5 y0=7.4 label="A" xt=0.5 yt=0.5 length=0.75 
	''')
#framebox B
xx=80
yy=0.5
ww=20
ww1=0.2

Flow('frameB.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(xx,yy,xx+ww,yy,xx+ww,yy+ww1,xx,yy+ww1,xx,yy))))
Plot('frameB','frameB.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=100 min2=0 max2=1 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n screenratio=0.3
	''')
Plot('labelB',None,
	'''
	box x0=29.5 y0=5.2 label="B" xt=0.5 yt=0.5 length=0.75 
	''')
Result('r_obs5d-3-0','Fig/r_obs5d-3.vpl frameA.vpl frameB.vpl labelA.vpl labelB.vpl','Overlay')
Result('r_drr5d-3-0','Fig/r_drr5d-3.vpl frameA.vpl frameB.vpl labelA.vpl labelB.vpl','Overlay')
Result('r_npef5d-3-0','Fig/r_recon5d-3.vpl frameA.vpl frameB.vpl labelA.vpl labelB.vpl','Overlay')

Flow('r_obs5d-cog','r_obs5d',' window n4=1 n5=1 f4=15 f5=7 | put n2=100 n3=1 ')
Flow('r_obs5d-cmg','r_obs5d',' window n2=1 f2=5 n3=1 f3=5  | put n2=210 n3=1')
Flow('r_drr5d-cog','r_drr5d',' window n4=1 n5=1 f4=15 f5=7 | put n2=100 n3=1 ')
Flow('r_drr5d-cmg','r_drr5d',' window n2=1 f2=5 n3=1 f3=5  | put n2=210 n3=1')
Flow('r_npef5d-cog','r_recon5d',' window n4=1 n5=1 f4=15 f5=7 | put n2=100 n3=1 ')
Flow('r_npef5d-cmg','r_recon5d',' window n2=1 f2=5 n3=1 f3=5  | put n2=210 n3=1')
Flow('r_obs5d-cog-zA','r_obs5d-cog','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_drr5d-cog-zA','r_drr5d-cog','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_npef5d-cog-zA','r_npef5d-cog','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_obs5d-cog-zB','r_obs5d-cog','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))
Flow('r_drr5d-cog-zB','r_drr5d-cog','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))
Flow('r_npef5d-cog-zB','r_npef5d-cog','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))

Greyz('r_obs5d-cog-zA','clip=0.2')
Greyz('r_drr5d-cog-zA','clip=0.2')
Greyz('r_npef5d-cog-zA','clip=0.2')
Greyz('r_obs5d-cog-zB','clip=0.2')
Greyz('r_drr5d-cog-zB','clip=0.2')
Greyz('r_npef5d-cog-zB','clip=0.2')

#framebox C
x=30
y=0.15
w=30
w1=0.25

Flow('frameC.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(x,y,x+w,y,x+w,y+w1,x,y+w1,x,y))))
Plot('frameC','frameC.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=210 min2=0 max2=1 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n screenratio=0.3
	''')
#label C
Plot('labelC',None,
	'''
	box x0=11.5 y0=7.4 label="A" xt=0.5 yt=0.5 length=0.75 
	''')
#framebox D
xx=135
yy=0.48
ww=30
ww1=0.25

Flow('frameD.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(xx,yy,xx+ww,yy,xx+ww,yy+ww1,xx,yy+ww1,xx,yy))))
Plot('frameD','frameD.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=210 min2=0 max2=1 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n screenratio=0.3
	''')
Plot('labelD',None,
	'''
	box x0=29.5 y0=5.2 label="B" xt=0.5 yt=0.5 length=0.75 
	''')
Result('r_obs5d-4-0','Fig/r_obs5d-4.vpl frameA.vpl frameB.vpl labelA.vpl labelB.vpl','Overlay')
Result('r_drr5d-4-0','Fig/r_drr5d-4.vpl frameA.vpl frameB.vpl labelA.vpl labelB.vpl','Overlay')
Result('r_npef5d-4-0','Fig/r_recon5d-4.vpl frameA.vpl frameB.vpl labelA.vpl labelB.vpl','Overlay')

Flow('r_obs5d-cmg-zA','r_obs5d-cmg','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_drr5d-cmg-zA','r_drr5d-cmg','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_npef5d-cmg-zA','r_npef5d-cmg','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_obs5d-cmg-zB','r_obs5d-cmg','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))
Flow('r_drr5d-cmg-zB','r_drr5d-cmg','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))
Flow('r_npef5d-cmg-zB','r_npef5d-cmg','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))

Greyz('r_obs5d-cmg-zA','clip=0.2')
Greyz('r_drr5d-cmg-zA','clip=0.2')
Greyz('r_npef5d-cmg-zA','clip=0.2')
Greyz('r_obs5d-cmg-zB','clip=0.2')
Greyz('r_drr5d-cmg-zB','clip=0.2')
Greyz('r_npef5d-cmg-zB','clip=0.2')


Flow('r_apef5_new r_mask5d2_new','r_obs5d_new r_mask5d_new',
     '''
     npef5 maskin=${SOURCES[1]} maskout=${TARGETS[1]} jump=2 
     a=4,2,2,1,1 niter=50 rect1=20 rect2=5 rect3=5 rect4=5 rect5=5 verb=y 
     ''')
Flow('r_recon5d_new','r_obs5d_new r_apef5_new r_mask5d_new',
     '''
     npef5_recon filt=${SOURCES[1]} mask=${SOURCES[2]} niter=100 verb=y  
     ''')

## transpose
#r_mask5d_newt.bin generated by Matlab
Flow('r_recon5d_new-t','r_recon5d_new','transp plane=24 | transp plane=35')
Flow('r_mask5d_newt','r_mask5d2t-0','put n1=250 o1=0 d1=0.004 n2=20 n3=20 n4=42 n5=20 o2=1 d2=1 o3=1 d3=1 o4=1 d4=1 o5=1 d5=1')

Flow('r_mask5d_new-t','r_mask5d_newt','transp plane=24 | transp plane=35')
#Flow('synth_obs5d-t','synth_obs5d','transp plane=24 | transp plane=35')
#Flow('synth_mask5d-t','synth_mask5d','transp plane=24 | transp plane=35')

Flow('r_apef5_new-t r_mask5d_new2-t','r_recon5d_new-t r_mask5d_new-t',
     '''
     npef5 maskin=${SOURCES[1]} maskout=${TARGETS[1]} jump=2 
     a=4,2,2,1,1 niter=50 rect1=50 rect2=10 rect3=10 rect4=5 rect5=5 verb=y 
     ''')
Flow('r_recon5d-t','r_recon5d_new-t r_apef5_new-t r_mask5d_new-t',
     '''
     npef5_recon filt=${SOURCES[1]} mask=${SOURCES[2]} niter=100 verb=y
     ''')
Flow('r_recon5d_new_transp','r_recon5d-t','transp plane=35 | transp plane=24')

Grey11('r_obs5d_new','')
Grey22('r_obs5d_new-2','r_obs5d_new','')
Grey33('r_obs5d_new-3','r_obs5d_new','')
Grey44('r_obs5d_new-4','r_obs5d_new','')

Grey11('r_recon5d_new','')
Grey22('r_recon5d_new-2','r_recon5d_new','')
Grey33('r_recon5d_new-3','r_recon5d_new','')
Grey44('r_recon5d_new-4','r_recon5d_new','')

"""
Grey11('r_recon5d_new_transp','')
Grey22('r_recon5d_new_transp-2','r_recon5d_new_transp','')
Grey33('r_recon5d_new_transp-3','r_recon5d_new_transp','')
Grey44('r_recon5d_new_transp-4','r_recon5d_new_transp','')
"""


#framebox E
x=80
y=0.15
w=60
w1=0.25

Flow('frameE.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(x,y,x+w,y,x+w,y+w1,x,y+w1,x,y))))
Plot('frameE','frameE.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=400 min2=0 max2=1 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n screenratio=0.3
	''')
#label E
Plot('labelE',None,
	'''
	box x0=12.5 y0=7.8 label="A" xt=0.5 yt=0.5 length=0.75 
	''')
#framebox F
xx=280
yy=0.6
ww=60
ww1=0.25

Flow('frameF.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	" ".join(map(str,(xx,yy,xx+ww,yy,xx+ww,yy+ww1,xx,yy+ww1,xx,yy))))
Plot('frameF','frameF.asc',
	'''
	dd type=complex form=native |
	graph min1=0 max1=400 min2=0 max2=1 pad=n plotfat=15 plotcol=4 
	wantaxis=n wanttitle=n yreverse=y scalebar=n screenratio=0.3
	''')
Plot('labelF',None,
	'''
	box x0=25.5 y0=4.5 label="B" xt=0.5 yt=0.5 length=0.75 
	''')
Result('r_obs5d_new-3-0','Fig/r_obs5d_new-3.vpl frameE.vpl frameF.vpl labelE.vpl labelF.vpl','Overlay')
Result('r_npef5d_new-3-0','Fig/r_recon5d_new-3.vpl frameE.vpl frameF.vpl labelE.vpl labelF.vpl','Overlay')

Flow('r_obs5d_new-cog','r_obs5d_new','window n4=1 n5=1 f4=10 f5=10 | put n2=400 n3=1')
Flow('r_npef5d_new-cog','r_recon5d_new','window n4=1 n5=1 f4=10 f5=10 | put n2=400 n3=1')
Flow('r_obs5d_new-cog-zA','r_obs5d_new-cog','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_npef5d_new-cog-zA','r_npef5d_new-cog','window  min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('r_obs5d_new-cog-zB','r_obs5d_new-cog','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))
Flow('r_npef5d_new-cog-zB','r_npef5d_new-cog','window  min2=%g max2=%g min1=%g max1=%g'%(xx,xx+ww,yy,yy+ww1))

Greyz('r_obs5d_new-cog-zA','clip=0.3')
Greyz('r_npef5d_new-cog-zA','clip=0.3')
Greyz('r_obs5d_new-cog-zB','clip=0.3')
Greyz('r_npef5d_new-cog-zB','clip=0.3')

Grey33fk('r_obs5d_new-3fk','r_obs5d_new','clip=0.05')
Grey33fk('r_npef5d_new-3fk','r_recon5d_new','clip=0.05')

















End()
