from rsf.proj import*
from rsf.prog import RSFROOT
from math import pi

# Data size: 101*32*32*5*5

def Grey3(data,other):
	Result(data,
       '''
       byte clip=0.2 |
       grey3 flat=n frame1=40 frame2=15 frame3=15 
       point1=0.8 point2=0.8 label2=HX label3=HX label1="Time" unit1=s unit2=trace unit3=trace title=
       screenratio=1.4 color=b font=104 %s'''%other)

def Grey(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.6 title=
       screenratio=0.2 color=b max1=0.4 font=104 %s'''%other)

def Greys(data,other):
	Result(data,
		'''put d1=0.004 o3=0 d2=1 d3=1 | byte clip=1.2 bar=bar.rsf| grey3 labelfat=4 font=2 titlefat=4 label2=HX label3=HY flat=n frame1=50 frame2=15 frame3=16 point1=0.85 point2=0.75 screenratio=1.2 label1=Time unit1=s  unit2=trace unit3=trace color=jet%s'''%(other))

def Grey3e(data,other,clip):
	Result(data,
       '''
       byte clip=%g |
       grey3 flat=n frame1=40 frame2=2 frame3=5 
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s title=
       screenratio=1.2 color=b font=104 %s'''%(clip,other))

def Greyfk(data,data0,other):
	Result(data,data0,
		'''put o1=0 n2=32 d2=1 o2=1 n3=32 d3=1 o3=1| fft1 | fft3 axis=2 pad=1| fft3 axis=3 pad=1| window max1=60| cabs |byte clip=100 allpos=y | grey3 labelfat=4 font=2 titlefat=4 flat=n label2="HX" unit2= label3="HY" unit1=Hz label1=Frequency frame1=10 frame2=15 frame3=20 point1=0.8 point2=0.8 title= screenratio=1.2 unit2=Wavenumber unit3=Wavenumber font=104  color=j %s '''%other)

## Load data
########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'synth_hyper'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

############################################################
## generate and process synthetic data
############################################################
Flow('hyper-clean-0 hyper-noisy-0 hyper-obs-0 hyper-drr-0 hyper-elrme-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}');quit"
    '''%vars(),stdin=0,stdout=-1)
    
Flow('hyper-clean','hyper-clean-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-noisy','hyper-noisy-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-obs','hyper-obs-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-drr','hyper-drr-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('hyper-elrme','hyper-elrme-0','put n2=32 n3=32 n4=5 n5=5 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')

Flow('hyper-clean-xy','hyper-clean','window n2=1 n3=1 f2=16 f3=16')
Flow('hyper-noisy-xy','hyper-noisy','window n2=1 n3=1 f2=16 f3=16')
Flow('hyper-obs-xy','hyper-obs','window n2=1 n3=1 f2=16 f3=16')
Flow('hyper-drr-xy','hyper-drr','window n2=1 n3=1 f2=16 f3=16')
Flow('hyper-elrme-xy','hyper-elrme','window n2=1 n3=1 f2=16 f3=16')

#Grey3('hyper-clean-xy','title=True')
#Grey3('hyper-noisy-xy','title=Noisy')
#Grey3('hyper-obs-xy','title=Observed ')
#Grey3('hyper-drr-xy','title=DRR')
#Grey3('hyper-elrme-xy','title=Proposed')

Flow('hyper-clean-hxhy','hyper-clean','window n4=1 n5=1 f4=3 f5=3')
Flow('hyper-noisy-hxhy','hyper-noisy','window n4=1 n5=1 f4=3 f5=3')
Flow('hyper-obs-hxhy','hyper-obs','window n4=1 n5=1 f4=3 f5=3')
Flow('hyper-drr-hxhy','hyper-drr','window n4=1 n5=1 f4=3 f5=3')
Flow('hyper-elrme-hxhy','hyper-elrme','window n4=1 n5=1 f4=3 f5=3')

Grey3('hyper-clean-hxhy','title=True frame1=50')
Grey3('hyper-noisy-hxhy','title=Noisy frame1=50')
Grey3('hyper-obs-hxhy','title=Observed frame1=50')
Grey3('hyper-drr-hxhy','title=DRR frame1=50')
Grey3('hyper-elrme-hxhy','title=Proposed frame1=50')

Greyfk('hyper-True-fkk','hyper-clean-hxhy','title=True')
Greyfk('hyper-noisy-fkk','hyper-noisy-hxhy','title=Noisy')
Greyfk('hyper-obs-fkk','hyper-obs-hxhy','title=Observed')
Greyfk('hyper-drr-fkk','hyper-drr-hxhy','title=DRR')
Greyfk('hyper-elrme-fkk','hyper-elrme-hxhy','title=Proposed')

Flow('hyper-drr-e','hyper-clean-hxhy hyper-drr-hxhy','add scale=1,-1 ${SOURCES[1]}')
Flow('hyper-elrme-e','hyper-clean-hxhy hyper-elrme-hxhy','add scale=1,-1 ${SOURCES[1]}')
Grey3('hyper-drr-e','title=DRR frame1=50')
Grey3('hyper-elrme-e','title=Proposed frame1=50')

Flow('hyper-n-drr-hxhy','hyper-noisy-hxhy hyper-drr-hxhy',' add scale=1,-1 ${SOURCES[1]}')
Flow('hyper-n-elrme-hxhy','hyper-noisy-hxhy hyper-elrme-hxhy',' add scale=1,-1 ${SOURCES[1]}')

Grey3('hyper-n-drr-hxhy','color=b color=b title=DRR')
Grey3('hyper-n-elrme-hxhy','color=b color=b title=Proposed')

Flow('hyper-simi1','hyper-n-drr-hxhy hyper-drr-hxhy','similarity other=${SOURCES[1]} niter=20 rect1=3 rect2=3 rect3=3')
Flow('hyper-simi2','hyper-n-elrme-hxhy hyper-elrme-hxhy','similarity other=${SOURCES[1]} niter=20 rect1=3 rect2=3 rect3=3 ')

Greys('hyper-simi1','color=j scalebar=y clip=0.8 minval=0 maxval=0.6 title="DRR" barlabel="Similarity"')
Greys('hyper-simi2','color=j scalebar=y clip=0.8 minval=0 maxval=0.6 title="Proposed" barlabel="Similarity"')

End()
