from rsf.tex import *
import os, sys
os.environ['PSTEXPENOPTS']='color=y fat=3 fatmult=1.5'
End('paper', use='amsmath,listings,algorithm,algorithmicx,[utf8]{inputenc},pdfpages,algpseudocode,morefloats', color='ALL')

