from rsf.proj import *

def Greycsg(data,other):
	Result(data,
       '''
       put o2=1 d2=5 d3=5 o3=1 | byte clip=0.5 | 
       grey3 flat=n frame1=100 frame2=38 frame3=20 label2=Shot
       title=Data point1=0.8 point2=0.8  label3=Receiver title= screenratio=1.3 %s
       '''%other)

def Greycmg(data,other):
	Result(data,
       '''
       byte clip=0.0024 |
       transp plane=23 |
       grey3 flat=n frame1=650 frame2=100 frame3=10 
       title=Data point1=0.8 point2=0.8 %s title=
       '''%other)

def Greycmg1(data,other):
	Result(data,
       '''
       byte |      
       grey3 flat=n frame1=750 frame2=25 frame3=100 
       title=Data point1=0.8 point2=0.8 %s title=
       '''%other)


def Vel(data,other):
	Result(data,
     '''
     grey color=j allpos=y bias=1.5 clip=0.7
     scalebar=y barreverse=y barunit=km/s
     label2=Midpoint unit2=km label1=Time unit1=s
     title="NMO Velocity"  %s
     '''%other )

def Pick3(data,other):
	Result(data,
       '''
       byte allpos=y gainpanel=all |
       transp plane=23 |
       grey3 flat=n frame1=750 frame2=100 frame3=10 
       label1=Time unit1=s color=j framelabelcol=VP_BLACK
       label3=Velocity unit3=km/s 
       label2=Midpoint unit2=km
       title="Velocity Scan" point1=0.8 point2=0.8 %s
       '''%other)

def Greymig(data,other):
	Result(data,
       '''
		window max1=5 min2=2.5 max2=7.5 |
       grey title="Prestack Kirchhoff Time Migration" 
	   label1=Depth unit1=km screenratio=1 %s
       '''%other)
Flow('fieldsr','fieldsr0','cp | scale axis=2 ')
Greycsg('fieldsr','title=Unblended')

### Blending
Flow('data-r','fieldsr','transp plane=23| reverse which=2 | transp plane=23 ')
Greycsg('data-r','title=source2')

Flow('dithert',None,'math output=1 n1=64 n2=1 | noise rep=y seed=201313 var=2 | spray axis=2 n=64 | transp ')
Flow('ditherx',None,'math output=1 n1=64 n2=1 | noise rep=y seed=201313 var=0 | spray axis=2 n=200 | transp ')

Flow('datt','data-r dithert','datstretch inv=y datum=${SOURCES[1]}')
Flow('datx','datt ditherx','transp plane=12 | datstretch inv=y datum=${SOURCES[1]} |transp plane=12')

## Blending
Flow('fieldsrs','fieldsr datx','transp plane=23 | add scale=1,1 ${SOURCES[1]}|transp plane=23 ')
Greycsg('fieldsrs','title="Blended"')

## Structure
ns0=6

dblends=[]
for i in range(64):
	dip='dip-%d'%i
	x0=i
	spray='spray-cube-%d'%i
	hyper='hyper-%d'%i
	dblend='dblend-%d'%i
	Flow(hyper,'fieldsrs','window n3=1 f3=%d | mutter half=n x0=%g v0=20'%(i,x0))
	Flow(dip,'fieldsrs','window n3=1 f3=%d | bandpass fhi=5 | dip rect1=%d rect2=%d'%(i,ns0-2+4+5,ns0-2+4+5))
	Flow(spray,[hyper,dip],
    	'''
     pwspray dip=${SOURCES[1]} ns=%d 
     ''' % (ns0)) 
	Flow(dblend,spray,'transp plane=12 | tsmf nfw=%d | transp plane=12 | window n2=1 f2=%d '%(ns0,ns0)) 
	dblends.append(dblend)
Flow('fieldsrs-db',dblends,'cat axis=3 ${SOURCES[1:%d]} | put d3=1 o3=0'%len(dblends))
Greycsg('fieldsrs-db','title="Deblended"')
 
Flow('fieldsrs-db-dif','fieldsrs fieldsrs-db','add scale=1,-1 ${SOURCES[1]}')
Flow('fieldsrs-db-err','fieldsr fieldsrs-db','add scale=1,-1 ${SOURCES[1]}') 
 
Greycsg('fieldsrs-db-dif','title="Blending noise"') 
Greycsg('fieldsrs-db-err','title="Deblending error"') 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

End()
