from rsf.proj import*
from rsf.prog import RSFROOT
from math import pi
# data directory
# /media/CHENYK2/SeismicDataYangkang/irr5d/data/

# Data size: 301*61*61

 
def Grey3(data,data0,other):
	Result(data,data0,
       '''
       window n4=1 n5=1 f4=8 f5=8|byte clip=0.3 |
       grey3 flat=n frame1=40 frame2=2 frame3=5 
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s title=
       screenratio=1.6 color=g %s'''%other)

def Grey(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.25 title=
       screenratio=0.7 color=g %s'''%other)
       
       
def Graph(data,other):
	Result(data,'graph label1="Time" label2="Amplitude" unit2= unit1="s" labelsz=10 labelfat=4 font=2 titlesz=10 titlefat=4 title="" wherexlabel=b wheretitle=t screenratio=0.5 %s' %other)

########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'Field5d'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
    sys.stderr.write('\nCannot find Matlab.\n')
    sys.exit(1)
    
T=3
niter=12
nniter=10
K=64
ll1=6
ll2=4
ll3=4
ss1=2
ss2=2
ss3=2
perc=4

put='d1=0.008 o1=0 n2=4 d2=1 o2=1 n3=4 d3=1 o3=1 n4=20 d4=1 o4=1 n5=20 d5=1 o5=1 '
############################################################
## with parameter
############################################################

Flow(['f5d-clean-0','f5d-noisy-0','f5d-obs-0','f5d-sgk-0','f5d-ksvd-0','f5d-ddtf-0'],[os.path.join(matROOT,matfun+'.m')],
     '''MATLABPATH=%(matlabpath)s %(matlab)s 
     -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}','${TARGETS[5]}',%(T)d,%(niter)d,%(nniter)d,%(K)d,%(ll1)d,%(ll2)d,%(ll3)d,%(ss1)d,%(ss2)d,%(ss3)d,%(perc)d);quit"
     '''%vars(),stdin=0,stdout=-1)

## Load data
Flow('f5d-clean','f5d-clean-0','put %s'%put)
Flow('f5d-noisy','f5d-noisy-0','put %s'%put)
Flow('f5d-obs','f5d-obs-0','put %s'%put)
Flow('f5d-sgk','f5d-sgk-0','put %s'%put)
Flow('f5d-ksvd','f5d-ksvd-0','put %s'%put)
Flow('f5d-ddtf','f5d-ddtf-0','put %s'%put)


Flow('f5d-noisy-xy','f5d-noisy','window n2=1 n3=1 f2=2 f3=2| put n2=400 n3=1')
Flow('f5d-obs-xy','f5d-obs','window n2=1 n3=1 f2=2 f3=2| put n2=400 n3=1')
Flow('f5d-sgk-xy','f5d-sgk','window n2=1 n3=1 f2=2 f3=2| put n2=400 n3=1')
Flow('f5d-ksvd-xy','f5d-ksvd','window n2=1 n3=1 f2=2 f3=2| put n2=400 n3=1')
Flow('f5d-ddtf-xy','f5d-ddtf','window n2=1 n3=1 f2=2 f3=2| put n2=400 n3=1')


Grey('f5d-noisy-xy','title=Noisy')
Grey('f5d-obs-xy','title=Observed ')
Grey('f5d-ksvd-xy','title=KSVD')
Grey('f5d-ddtf-xy','title=DDTF')
Grey('f5d-sgk-xy','title=SGK')


## Creating framebox
x=140
y=0.1
w=60
w1=0.3


Flow('z-obs','f5d-obs-xy','window min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('z-ksvd','f5d-ksvd-xy','window min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('z-ddtf','f5d-ddtf-xy','window min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))
Flow('z-sgk','f5d-sgk-xy','window min2=%g max2=%g min1=%g max1=%g'%(x,x+w,y,y+w1))

Grey('z-obs','title=Observed clip=0.25 screenratio=0.75')
Grey('z-ksvd','title=KSVD clip=0.25 screenratio=0.75')
Grey('z-ddtf','title=DDTF clip=0.25 screenratio=0.75')
Grey('z-sgk','title=SGK clip=0.25 screenratio=0.75')

Flow('frame.asc',None,'echo %s n1=10 data_format=ascii_float in=$TARGET'% \
	string.join(map(str,(x,y,x+w,y,x+w,y+w1,x,y+w1,x,y))))
Plot('frame','frame.asc',
	'''
	dd type=complex form=native |
	graph min1=1 max1=400 min2=0 max2=0.8 pad=n plotfat=15 plotcol=4 screenratio=0.7
	wantaxis=n wanttitle=n yreverse=y 
	''')

Result('f5d-obs','Fig/f5d-obs-xy.vpl frame','Overlay')
Result('f5d-ksvd','Fig/f5d-ksvd-xy.vpl frame','Overlay')
Result('f5d-ddtf','Fig/f5d-ddtf-xy.vpl frame','Overlay')
Result('f5d-sgk','Fig/f5d-sgk-xy.vpl frame','Overlay')




End()
