from rsf.proj import*
from rsf.prog import RSFROOT
from math import *

def Grey(data,other): 
      Result(data,
      '''
      put d1=0.004 d2=1 o1=0 o2=0 |
      grey clip=0.4 transp=y yreverse=y color=g 
      wanttitle=y flat=n labelfat=4 font=2 titlefat=4
      label2=Trace  unit2="" label1="Time" unit1=s title=""
      wherexlabel=t scalebar=n wheretitle=b screenratio=1.4  color=r %s
      '''
      %other)

def Greyn(data,other): 
      Result(data,
      '''
      put d1=1 d2=1 o1=0 o2=0 | byte  clip=0.6 | 
      grey clip=0.4 transp=y yreverse=y color=g
      wanttitle=y flat=n labelfat=4 font=2 titlefat=4 
      label2=Trace  unit2="" label1="Time sampling number" unit1= title=""
      wherexlabel=t scalebar=n wheretitle=b screenratio=1.4  color=r %s
      '''
      %other)
       
def Graph(data,other):
	Result(data,'graph label1="Noise variances" label2="SNR (dB)" unit2= unit1="s" labelsz=10 labelfat=4 font=2 titlesz=10 titlefat=4 title="" wherexlabel=b wheretitle=t plotfat=10 %s' %other)
	
def Graphplot(data,other):
	Plot(data,'graph label1="Noise variances" label2="SNR" unit2=dB labelsz=10 labelfat=4 font=2 titlesz=10 titlefat=4 title="" wherexlabel=b wheretitle=t plotfat=10 %s' %other)


def Greyz(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.4 title= screenratio=0.6
       color=g %s'''%other)

def Wig(data,other): 
	Result(data,'''
				wiggle transp=y yreverse=y screenratio=1.4
				label2=Trace unit2="" label1=Time unit1="s" 
				title="" wherexlabel=b wheretitle=t poly=y 
				wheretitle=t wherexlabel=b clip=0.3 labelsz=10 %s'''%other)

def WigC(data,other): 
	Result(data,'''
				wiggle transp=y yreverse=y screenratio=1.4
				label2=Trace unit2="" label1=Time unit1="s" 
				title="" wherexlabel=b wheretitle=t poly=y 
				wheretitle=t wherexlabel=b clip=1.5 labelsz=10 %s'''%other)

########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'SYN1_R'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

###########################################################
# generate and process synthetic data
###########################################################
Flow('syn1_dc-0 syn1_dn-0 syn1_ssa-0 syn1_sst-0 syn1_snrs-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}');quit"
    '''%vars(),stdin=0,stdout=-1)
     
Flow('syn1','syn1_dn-0','put n1=401 n2=200  d1=0.004 n1=401 n2=200')
Flow('syn1-c','syn1_dc-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')

#Flow('syn1-ssa','syn1','fxmssa k=4 flo=0 fhi=40')
Flow('syn1-sst-fxmssa','syn1','fxmssa k=3 n=2 flo=0 fhi=40')

Flow('syn1-ssa','syn1_ssa-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-sst','syn1_sst-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')

Flow('syn1-ssa-n','syn1 syn1-ssa','add scale=1,-1 ${SOURCES[1]}')
Flow('syn1-sst-n','syn1 syn1-sst','add scale=1,-1 ${SOURCES[1]}')

#Flow('syn1-sst-n syn1-sst-t','syn1-sst-n-t syn1-c','ortho sig=${SOURCES[1]} sig2=${TARGETS[1]} rect1=3 rect2=3 eps=0.1')

Grey('syn1-c','clip=0.4 title=Clean')
Grey('syn1','clip=0.4 title=Noisy')
Grey('syn1-ssa','clip=0.4 title=TSVD')
Grey('syn1-sst','clip=0.4  title=GROUSE')
Grey('syn1-ssa-n','clip=0.4 title=TSVD') 
Grey('syn1-sst-n','clip=0.4 title=GROUSE')


Flow('snrs','syn1_snrs-0','put n1=10 n2=4 d1=1 d2=1')

Flow('sigma','snrs','window n2=1')
Flow('snr1','snrs','window n2=1 f2=1')
Flow('snr2','snrs','window n2=1 f2=2 | math output="input-0.5"')
Flow('snr3','snrs','window n2=1 f2=3')

Flow('snr1s','sigma snr1','cmplx ${SOURCE} ${SOURCES[1]}')

Flow('snr2s','sigma snr2','cmplx ${SOURCE} ${SOURCES[1]}')
Flow('snr3s','sigma snr3','cmplx ${SOURCE} ${SOURCES[1]}')

Flow('snr1st','snr1s','cp')
Flow('snr2st','snr2s','cp')
Flow('snr3st','snr3s','cp')

Graphplot('snr1s','min2=-20 max2=21 symbol="o" symbolsz=8 plotcol=7 ')
Graphplot('snr2s','min2=-20 max2=21 symbol="v" symbolsz=8 plotcol=5 wantaxis=n')
Graphplot('snr3s','min2=-20 max2=21 symbol="*" symbolsz=8 plotcol=3 wantaxis=n')

Graphplot('snr1st','min2=-20 max2=21   plotcol=7 wantaxis=n')
Graphplot('snr2st','min2=-20 max2=21   plotcol=5 wantaxis=n')
Graphplot('snr3st','min2=-20 max2=21   plotcol=3 wantaxis=n')


Plot('label1',None,
	'''
	box x0=6.0 y0=3.4 label="Raw data" xt=-0.5 yt=-0.5 length=1 
	''')
	
Plot('label2',None,
	'''
	box x0=6 y0=5.4 label="TSVD" xt=-0.5 yt=-0.5 length=1 
	''')
	
Plot('label3',None,
	'''
	box x0=8 y0=5.4 label="GROUSE" xt=0.5 yt=0.5 length=1 
	''')
		
		
Result('snr-n','snr1s snr2s snr3s snr1st snr2st snr3st label1 label2 label3','Overlay')


#spiky noise
Flow('syn1-sp','syn1-c','saltpepper seed=201516 var=0 den=5 inten=1')


###########################################################
# generate and process synthetic data
###########################################################
matfun = 'SYN1_SP'
Flow('syn1_sp_ssa-0 syn1_sp_sst-0',[os.path.join(matROOT,matfun+'.m'),'syn1-c','syn1-sp'],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${SOURCES[1]}','${SOURCES[2]}','${TARGETS[0]}','${TARGETS[1]}');quit"
    '''%vars(),stdin=0,stdout=-1)

Flow('syn1-sp-ssa','syn1_sp_ssa-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-sp-sst','syn1_sp_sst-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')

Flow('syn1-sp-ssa-n','syn1-sp syn1-sp-ssa','add scale=1,-1 ${SOURCES[1]}')
Flow('syn1-sp-sst-n','syn1-sp syn1-sp-sst','add scale=1,-1 ${SOURCES[1]}')
Grey('syn1-sp','clip=0.4 title=Noisy')
Grey('syn1-sp-ssa','clip=0.4 title=TSVD')
Grey('syn1-sp-sst','clip=0.4 title=GROUSE')
Grey('syn1-sp-ssa-n','clip=0.4 title=TSVD')
Grey('syn1-sp-sst-n','clip=0.4 title=GROUSE')

###########################################################
# generate and process synthetic data
###########################################################
matfun = 'SYN1_BD'
Flow('syn1_bd_ssa-0 syn1_bd_sst-0',[os.path.join(matROOT,matfun+'.m'),'syn1-c','syn1-bd'],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${SOURCES[1]}','${SOURCES[2]}','${TARGETS[0]}','${TARGETS[1]}');quit"
    '''%vars(),stdin=0,stdout=-1)

#blending noise
Flow('syn1-bd','syn1-c','selfblend seed=201718 range=1.0 var=5')
Flow('syn1-bd-ssa','syn1_bd_ssa-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-bd-sst','syn1_bd_sst-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')

Flow('syn1-bd-ssa-n','syn1-bd syn1-bd-ssa','add scale=1,-1 ${SOURCES[1]}')
Flow('syn1-bd-sst-n','syn1-bd syn1-bd-sst','add scale=1,-1 ${SOURCES[1]}')
Grey('syn1-bd','clip=0.4 title=Noisy')
Grey('syn1-bd-ssa','clip=0.4 title=TSVD')
Grey('syn1-bd-sst','clip=0.4 title=GROUSE')
Grey('syn1-bd-ssa-n','clip=0.4 title=TSVD')
Grey('syn1-bd-sst-n','clip=0.4 title=GROUSE')

###########################################################
# generate and process synthetic data
###########################################################
matfun = 'SYN1_N'

Flow('noise_401_200_n-0 noise_401_200_ssa_k1-0 noise_401_200_sst_k1-0 noise_401_200_ssa_k3-0 noise_401_200_sst_k3-0 noise-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}','${TARGETS[5]}');quit"
    '''%vars(),stdin=0,stdout=-1)
    
#sensitivity to noise
Flow('syn1-noise','noise_401_200_n-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-ssak1','noise_401_200_ssa_k1-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-sstk1','noise_401_200_sst_k1-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-ssak3','noise_401_200_ssa_k3-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Flow('syn1-sstk3','noise_401_200_sst_k3-0','put n1=401 n2=200 d1=0.004 n1=401 n2=200')
Grey('syn1-noise','clip=0.4 title=Noise color=g')
Grey('syn1-ssak1','clip=0.4 title="TSVD (K=1)" color=g')
Grey('syn1-sstk1','clip=0.4 title="GROUSE (K=1)" color=g')
Grey('syn1-ssak3','clip=0.4 title="TSVD (K=3)" color=g')
Grey('syn1-sstk3','clip=0.4 title="GROUSE (K=3)" color=g')

Flow('noise','noise-0','put n1=10 n2=4 d1=1 d2=1')
Flow('k','noise','window n2=1')
Flow('e1','noise','window n2=1 f2=1')
Flow('e2','noise','window n2=1 f2=2 ')
Flow('e3','noise','window n2=1 f2=3')

Flow('e1s','k e1','cmplx ${SOURCE} ${SOURCES[1]}')

Flow('e2s','k e2','cmplx ${SOURCE} ${SOURCES[1]}')
Flow('e3s','k e3','cmplx ${SOURCE} ${SOURCES[1]}')

Flow('e1st','e1s','cp')
Flow('e2st','e2s','cp')
Flow('e3st','e3s','cp')

Graphplot('e1s','min2=0 max2=40000 symbol="o" symbolsz=8 plotcol=7 label1="Rank" label2="Noise Energy" unit2=')
Graphplot('e2s','min2=0 max2=40000 symbol="v" symbolsz=8 plotcol=5 wantaxis=n')
Graphplot('e3s','min2=0 max2=40000 symbol="*" symbolsz=8 plotcol=3 wantaxis=n')

Graphplot('e1st','min2=0 max2=40000   plotcol=7 wantaxis=n')
Graphplot('e2st','min2=0 max2=40000   plotcol=5 wantaxis=n')
Graphplot('e3st','min2=0 max2=40000   plotcol=3 wantaxis=n')


Plot('label4',None,
	'''
	box x0=6 y0=7.2 label="Input noise" xt=-0.5 yt=-0.5 length=1 
	''')
Plot('label5',None,
	'''
	box x0=6.4 y0=3.7 label="TSVD" xt=-0.5 yt=0.5 length=1 
	''')
		
Plot('label6',None,
	'''
	box x0=8 y0=2.4 label="GROUSE" xt=0.5 yt=-0.5 length=1 
	''')
		
		
Result('e-n','e1s e2s e3s e1st e2st e3st label4 label5 label6','Overlay')


End()
