from rsf.tex import*
os.environ['PSTEXPENOPTS']='color=y fat=3 fatmult=1.5'

## add pdflatex into default PATH
import sys
env=Environment()
if sys.platform == 'darwin':
    env['ENV']['PATH'] = ':'.join(['/opt/local/bin',env['ENV']['PATH']])

Paper('dealiaseeage',lclass='vie16',use='listings, amsmath,subfigure')

Paper('seg2015_dealiase',lclass='segabs',use='listings, amsmath,subfigure')
env.Command('seg2015_dealiase_final.pdf','seg2015_dealiase_final.ltx','pdflatex $SOURCE')

Paper('dealiasejge',lclass='iopart',use='listings,harvard,subfigure,graphics,amsmath',    
include=r'''
\newcommand{\gguide}{{\it Preparing graphics for IOP journals}}
''')

## First revision
Paper('dealiase_revise1',lclass='geophysics',options='manuscript,revised',use='listings,amsmath')
Command('dealiase_revise_plain1.tex','dealiase_revise1.tex','cp $SOURCE $TARGET')
Paper('dealiase_revise_plain1',lclass='geophysics',options='manuscript',use='amsmath')

Paper('dealiase_revise2',lclass='geophysics',options='manuscript,revised',use='listings,amsmath')
Command('dealiase_revise_plain2.tex','dealiase_revise2.tex','cp $SOURCE $TARGET')
Paper('dealiase_revise_plain2',lclass='geophysics',options='manuscript',use='amsmath')

Paper('reply1',use='hyperref,listings')
Paper('reply2',use='hyperref,amsmath,listings')
Paper('reply3',use='hyperref,amsmath,listings')

Paper('dealiase',lclass='geophysics',options='manuscript',use='listings,amsmath,subfigure,natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')
          
          
Paper('ieee_cs',lclass='IEEEtran',options='conference',use='graphicx,subfigure,amsmath')

Paper('ieee_r1',lclass='IEEEtran',options='10pt',use='cite,ifthen,seg,color,graphicx,subfigure,amsmath')
Paper('ieee_r2',lclass='IEEEtran',options='10pt',use='cite,ifthen,seg,color,graphicx,subfigure,amsmath')
Paper('ieee_r3',lclass='IEEEtran',options='10pt',use='cite,ifthen,seg,color,graphicx,subfigure,amsmath')
 
Paper('ieee_dealiase',lclass='IEEEtran',options='10pt',use='cite,ifthen,seg,color,graphicx,subfigure,amsmath')

env.Command(['ieee','IEEEtran.bst','IEEEtran.cls'],[os.getenv('HOME')+'/chenyk.open/temp/ieee/IEEEtran.bst',os.getenv('HOME')+'/chenyk.open/temp/ieee/IEEEtran.cls'],'cp  ${SOURCES[0]}  ${TARGETS[1]} && cp  ${SOURCES[1]}  ${TARGETS[2]} ')
           
End(lclass='geophysics',use='listings,amsmath')
