from rsf.proj import *
from math import pi
from rsf.prog import RSFROOT
#from rsf.recipes.beg import server as private

def Grey(data,other):
	Result(data,
	'''
    window n4=1 n5=1 f4=1 f5=1 | 
    byte allpos=n clip=1.0 |
    grey3 title=  label2=Hx label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=4 frame3=4
    parallel2=n o2num=0 d2num=0.1 n2tic=4 screenratio=1.3
    font=2 labelfat=2 titlefat=2 %s
    '''%other)

def Greyfk(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=1 f5=1 | fft1 axis=1 | fft axis=2 |fft axis=3 |cabs|
    byte allpos=y clip=5.0 |window max1=40|
    grey3 title=  label2=Hx label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=4 frame3=4
    parallel2=n o2num=0 d2num=10 n2tic=10 screenratio=1.3
    font=2 labelfat=2 titlefat=2 color=j  %s
    '''%other)

def Greym(data,other):
	Result(data,
	'''
    window n4=1 n5=1 | 
    byte allpos=n clip=1.1 bar=bar.rsf |
    grey3 title=  label2=Hx label3=Hy label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=5 frame3=5
    parallel2=n o2num=0 d2num=0.1 n2tic=4 screenratio=1.3
    font=2 labelfat=2 titlefat=2 scalebar=y %s
    '''%other)

def Grey2(data,data0,other):
	Result(data,data0,
	'''
    window n2=1 f2=4 n3=1 f3=4 | 
    byte allpos=n clip=1.0 |
    grey3 title=  label2=X label3=Y label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=1 frame3=4
    parallel2=n o2num=0 d2num=0.1 n2tic=4 screenratio=1.3
    font=2 labelfat=2 titlefat=2 %s
    '''%other)   

def Grey3(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=1 f5=1 | put n2=4096 n3=1 |window n2=4032|
    grey title=  label2=Trace label3=Trace label1="Time" unit1=s 
    point1=0.8 point2=0.7 frame1=50 frame2=4 frame3=4
    parallel2=n o2num=0 d2num=0.1 n2tic=4 screenratio=0.3
    font=2 labelfat=2 titlefat=2 clip=0.5 %s
    '''%other)  
def Grey3fk(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=1 f5=1|fft1|fft3 axis=2|fft3 axis=3|cabs | window max1=50 | put n2=4096 n3=1 |window n2=4032| put o2=1 d2=1| window f2=400 n2=400|
    grey title=  label2="Wavenumber Trace" label3=Trace label1="Frequency" unit1=Hz 
    point1=0.8 point2=0.7 frame1=50 frame2=4 frame3=4
    parallel2=n screenratio=0.3 color=j allpos=y
    font=2 labelfat=2 titlefat=2 clip=50 %s
    '''%other)   
    
def Grey3fk2(data,data0,other):
	Result(data,data0,
	'''
    window n4=1 n5=1 f4=1 f5=1|fft1|fft3 axis=2|fft3 axis=3|cabs | window max1=50 | byte allpos=y clip=50 bar=bar.rsf |
    grey3 title=  label2="Wavenumber Trace" label3=Trace label1="Frequency" unit1=Hz 
    point1=0.8 point2=0.7 frame1=20 frame2=32 frame3=32 flat=n
    parallel2=n  screenratio=1.3 color=j
    font=2 labelfat=2 titlefat=2 %s
    '''%other)   

########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'Hyper5da'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

put="n1=101 o1=0 d1=0.004 n2=64 n3=64 n4=5 n5=5 o2=1 d2=1 o3=1 d3=1 o4=1 d4=1 o5=1 d5=1"
############################################################
## generate and process synthetic data
############################################################
Flow('ha_obs5d-0 ha_mask5d-0 ha_drr5d-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}');quit"
    '''%vars(),stdin=0,stdout=-1)
Flow('ha_obs5d','ha_obs5d-0',' put %s'%put)
Flow('ha_mask5d','ha_mask5d-0',' put %s'%put)
Flow('ha_drr5d','ha_drr5d-0',' put %s'%put)
Flow('ha_obs5d_comp','ha_obs5d ha_mask5d','add mode=p ${SOURCES[1]}')

# 5D APEF
Flow('ha_apef5 ha_mask5d2','ha_obs5d ha_mask5d',
     '''
     npef5 maskin=${SOURCES[1]} maskout=${TARGETS[1]} jump=2
     a=4,2,2,1,1 niter=100 rect1=50 rect2=10 rect3=10 rect4=5 rect5=5 verb=y
     ''')
     
Flow('ha_recon5d','ha_obs5d ha_apef5 ha_mask5d',
     '''
     npef5_recon filt=${SOURCES[1]} mask=${SOURCES[2]} niter=100 verb=y 
     ''')

Grey('ha_obs5d','')
Greyfk('ha_obs5d-fk','ha_obs5d','')

Greym('ha_mask5d','color=j')
Greym('ha_mask5d2','color=j')
Grey('ha_recon5d','')

Grey2('ha_obs5d-2','ha_obs5d','')
Grey2('ha_recon5d-2','ha_recon5d','')

Grey3('ha_obs5d-3','ha_obs5d','')
Grey3('ha_recon5d-3','ha_recon5d','')
Grey3('ha_drr5d-3','ha_drr5d','')

Grey3fk('ha_obs5d-3fk','ha_obs5d','')
Grey3fk('ha_recon5d-3fk','ha_recon5d','')
Grey3fk('ha_drr5d-3fk','ha_drr5d','')

Grey3fk2('ha_obs5d-3fk2','ha_obs5d','')
Grey3fk2('ha_recon5d-3fk2','ha_recon5d','')
Grey3fk2('ha_drr5d-3fk2','ha_drr5d','')

End()
