from rsf.proj import *

exe=Program('mod2d.c')

def Graph(data,other):
	Plot(data,
		'''
		graph title= allpos=y  yreverse=y wantaxis=n
		scalebar=n bartype=v barlabel="V"  barunit="m/s" clip=4500 
		%s wheretitle=t wherexlabel=b'''%other)

#try different spatial distances
d2=7.5
d2=15
		
Flow('top',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=1800')
Flow('mid',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=1800')
Flow('bot',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=1800')
Flow('vel','top mid bot','cat axis=1 ${SOURCES[1:3]} | smooth rect1=3 |window f1=30 n1=125|put o1=0 | put d2=%g'%d2)

#Flow('vel',None,'spike n1=200 n2=200 d1=15 d2=15 | math output="x1*0.5+1500" ')

Flow('src',None,
     '''
     spike n1=125 n2=115 d1=7.5 d2=7.5 nsp=2
     k1=50,50
     k2=50,60
     mag=4000 | smooth rect1=2 rect2=2 repeat=1 
     ''')

Flow('sov','vel src','add mode=a ${SOURCES[1]} ')
Result('sov','vel src','add mode=a ${SOURCES[1]}| put o2=0 o1=0 |grey allpos=y bias=1500 color=e scalebar=n maxval=2200 title="Source Location and Velocity Model" barlabel="V" barunit="m/s" label1=Depth label2=Distance unit1=m unit2=m pclip=100')

#Flow('s',None,'spike n1=20 n2=1 d1=240 o1=36 | math output=24')
Flow('r',None,'spike n1=25 n2=1 d1=15 o1=262.5 | math output=255')
#Graph('s','min2=0 max2=888 min1=0 max1=4632 symbol="*" symbolsz=20 wantlabel=n plotcol=4')
Graph('r','min2=225 max2=1567.5 min1=0 max1=892.5 symbol="v" symbolsz=14 wantlabel=n plotcol=6')

Result('vel-sr','Fig/sov.vpl r','Overlay')

nt=2001
dt=0.001

Flow('data0 snaps data_v0','vel %s'%exe[0],
     '''
     ./${SOURCES[1]} snaps=${TARGETS[1]} dat_v=${TARGETS[2]} verb=y cmplx=n vref=1500 ps=y nt=%d dt=%g snap=1 abc=y nbt=30 ct=0.01 src=0 n_srcs=2
     spz=50,50
     spx=50,60
     f0=30,30
     t0=0.1,0.21
     A=1,1
     '''%(nt,dt))

Result('snaps','window j3=10 | grey gainpanel=a')

Result('snap1','snaps','window n3=1 f3=340|grey label1="Depth" unit1=m title="Time=0.34s"' )
Result('snap2','snaps','window n3=1 f3=720|grey label1="Depth" unit1=m title="Time=0.72s"' )


#Result('snap1','snaps sov','window n3=1 f3=100| add scale=1,1 ${SOURCES[1]} |  grey label1="Depth" unit1=m title="Time=0.34s"' )
#Result('snap2','snaps sov','window n3=1 f3=250| add scale=1,1 ${SOURCES[1]}  | grey label1="Depth" unit1=m title="Time=0.72s"' )


#uncomment the following to see the synthetic result
#Flow('data','data0','noise var=0.000 type=y seed=12005')

tmp = 5
snaps_list1 = []
src_list = ''
for i in range(tmp):
    mask = 'mask%d' %i
    data = 'data_mask%d' %i
    img = 'img%d' %i
    snaps = 'snaps%d' %i
    
    Flow(mask,None,'spike n1=55 mag=1 k1=%d l1=%d | sfdd type=int' %(11*i+1,11*i+3))
    Flow(data,['data',mask],'headercut mask=${SOURCES[1]}')
    Flow([img,snaps],['vel',data,'%s'%exe[0]],
         '''
         ./${SOURCES[2]} snaps=${TARGETS[1]} verb=y cmplx=n vref=1500 ps=y snap=1 abc=y nbt=30 ct=0.01 mig=y dat=${SOURCES[1]}
         ''')
    Result(snaps,'window j3=10 | grey gainpanel=a')
    Result(img,'grey')
    snaps_list1 += [snaps]
    src_list += ' ${SOURCES[%d]}' %(i+1)

Result('data_mask0','grey wanttitle=n')
Result('data_mask1','grey wanttitle=n')
Result('data_mask2','grey wanttitle=n')
Result('data_mask3','grey wanttitle=n')
Result('data_mask4','grey wanttitle=n')

Flow('ccr0',snaps_list1,'math a=${SOURCES[1]} b=${SOURCES[2]} c=${SOURCES[3]} d=${SOURCES[4]} output="input^2*a^2*b^2*c^2*d^2" ')
Result('ccr0','window j3=10 | grey gainpanel=a pclip=99.9')

Flow('location0','ccr0','stack axis=3 | pad beg1=30 end1=40 beg2=30 end2=50|put o1=0 o2=0|smooth rect1=3 rect2=3') 
Result('location0','sfgrey pclip=99.95  allpos=y label1=Depth label2=Distance unit1=m unit2=m title="Source Location Image" ')


End()
