from rsf.proj import*
from rsf.prog import RSFROOT
from math import pi
# Data size: 301*61*61
 
def Grey3(data,other):
	Result(data,
       '''
       byte clip=0.2 |
       grey3 flat=n frame1=50 frame2=5 frame3=5
       point1=0.8 point2=0.8 label2= label3= label1="Time" unit1=s unit2=trace unit3=trace title=
       screenratio=1.4 color=g font=104 %s'''%other)

def Grey3e(data,other,clip):
	Result(data,
       '''
       byte clip=%g |
       grey3 flat=n frame1=50 frame2=5 frame3=5 
       point1=0.8 point2=0.8 label2=X label3=Y unit2=trace unit3=trace label1="Time" unit1=s title=
       screenratio=1.4 color=g font=104 %s'''%(clip,other))

def Grey3s(data,other,clip):
	Result(data,
       '''
       byte clip=%g  gainpanel=all  bar=bar.rsf|
       grey3 flat=n frame1=50 frame2=5 frame3=5
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s title=
       screenratio=1.4 color=j scalebar=y maxval=1 minval=0 font=104 %s'''%(clip,other))
       
def Grey(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.9 title=
       screenratio=1.4 color=g %s'''%other)

def Wig(data,other):
	Result(data,
       '''
       wiggle poly=y transp=y yreverse=y label2=Trace label1="Time" unit1=s clip=0.4 title=
       screenratio=1.4 color=g %s'''%other)

def Graph(data,other):
	Result(data,'graph label1="Time" label2="Amplitude" unit2= unit1="s" labelsz=10 labelfat=4 font=2 titlesz=10 titlefat=4 title=" Amplitude comparison" wherexlabel=b wheretitle=t screenratio=0.5 %s' %other)
	
## Load data
########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'synth'
#matfun='~/home/bm/mrc5dok/matfun'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))
##############################################
#insert path tensor 

import sys 
sys.path.insert(0, '/home/bm/mrc5d/tensor_toolbox_2.4')

#TENSOR_PATH= '/home/bm/mrc5dok/matfun/tensor_toolbox_2.4'

###################################################################3

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

############################################################
## generate and process synthetic data
############################################################
Flow('synth-original-0 synth-noisy-0 synth-obs-0 synth-hooi-0 synth-drr-0 synth-mrc-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s; %(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}','${TARGETS[5]}');quit"
    '''%vars(),stdin=0,stdout=-1)

Flow('synth-original','synth-original-0',' put n2=10 n3=10 n4=10 n5=10 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-noisy','synth-noisy-0','put n2=10 n3=10 n4=10 n5=10 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-obs','synth-obs-0','put n2=10 n3=10 n4=10 n5=10 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-hooi','synth-hooi-0','put n2=10 n3=10 n4=10 n5=10 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-drr','synth-drr-0','put n2=10 n3=10 n4=10 n5=10 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-mrc','synth-mrc-0','put n2=10 n3=10 n4=10 n5=10 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')

Flow('synth-original-xy','synth-original','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-noisy-xy','synth-noisy','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-obs-xy','synth-obs','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-hooi-xy','synth-hooi','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-drr-xy','synth-drr','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-mrc-xy','synth-mrc','window n2=1 n3=1 f2=5 f3=5')

Grey3('synth-original-xy','title=Original frame1=50 label2=X label3=Y')
Grey3('synth-noisy-xy','title=Noisy frame1=50 label2=X label3=Y')
Grey3('synth-obs-xy','title=Observed frame1=50 label2=X label3=Y')
Grey3('synth-hooi-xy','title=HOOI frame1=50 label2=X label3=Y')
Grey3('synth-drr-xy','title=DRR frame1=50 label2=X label3=Y')
Grey3('synth-mrc-xy','title=Proposed frame1=50 label2=X label3=Y')

Flow('synth-original-hxhy','synth-original','window n4=1 n5=1 f4=8 f5=8')
Flow('synth-noisy-hxhy','synth-noisy','window n4=1 n5=1 f4=8 f5=8')
Flow('synth-obs-hxhy','synth-obs','window n4=1 n5=1 f4=8 f5=8')
Flow('synth-hooi-hxhy','synth-hooi','window n4=1 n5=1 f4=8 f5=8')
Flow('synth-drr-hxhy','synth-drr','window n4=1 n5=1 f4=8 f5=8')
Flow('synth-mrc-hxhy','synth-mrc','window n4=1 n5=1 f4=8 f5=8')

Grey3('synth-original-hxhy','title=Original frame1=50 label2=HX label3=HY')
Grey3('synth-noisy-hxhy','title=Noisy frame1=50 label2=HX label3=HY')
Grey3('synth-obs-hxhy','title=Observed frame1=50 label2=HX label3=HY')
Grey3('synth-hooi-hxhy','title=HOOI frame1=50 label2=HX label3=HY')
Grey3('synth-drr-hxhy','title=DRR frame1=50 label2=HX label3=HY')
Grey3('synth-mrc-hxhy','title=Proposed frame1=50 label2=HX label3=HY')

Flow('s-c','synth-original-hxhy','window n2=1 n3=1 f2=4 f3=4')
Flow('s-n','synth-noisy-hxhy','window n2=1 n3=1 f2=4 f3=4')
Flow('s-obs','synth-obs-hxhy','window n2=1 n3=1 f2=4 f3=4')
Flow('s-hooi','synth-hooi-hxhy','window n2=1 n3=1 f2=4 f3=4')
Flow('s-drr','synth-drr-hxhy','window n2=1 n3=1 f2=4 f3=4')
Flow('s-mrc','synth-mrc-hxhy','window n2=1 n3=1 f2=4 f3=4')

Flow('synth-ss','s-c s-mrc s-drr s-hooi s-obs s-n','cat axis=2 ${SOURCES[1:6]}')
Graph('synth-ss','plotfat=10 plotcol="5,3,6,1,4,7"')

Flow('synth-hooi-xy-e','synth-original-xy synth-hooi-xy','add scale=1,-1 ${SOURCES[1]}')
Flow('synth-drr-xy-e','synth-original-xy synth-drr-xy','add scale=1,-1 ${SOURCES[1]}')
Flow('synth-mrc-xy-e','synth-original-xy synth-mrc-xy','add scale=1,-1 ${SOURCES[1]}')
Grey3e('synth-hooi-xy-e','title=HOOI frame1=50 label2=X label3=Y',0.9)
Grey3e('synth-drr-xy-e','title=DRR frame1=50 label2=X label3=Y',0.9)
Grey3e('synth-mrc-xy-e','title=Proposed frame1=50 label2=X label3=Y',0.9)

Flow('synth-hooi-hxhy-e','synth-original-hxhy synth-hooi-hxhy','add scale=1,-1 ${SOURCES[1]}')
Flow('synth-drr-hxhy-e','synth-original-hxhy synth-drr-hxhy','add scale=1,-1 ${SOURCES[1]}')
Flow('synth-mrc-hxhy-e','synth-original-hxhy synth-mrc-hxhy','add scale=1,-1 ${SOURCES[1]}')
Grey3e('synth-hooi-hxhy-e','title=HOOI frame1=50 label2=HX label3=HY',0.9)
Grey3e('synth-drr-hxhy-e','title=DRR frame1=50 label2=HX label3=HY',0.9)
Grey3e('synth-mrc-hxhy-e','title=Proposed frame1=50 label2=HX label3=HY',0.9)

Flow('synth-original-xy-t','synth-original-xy','math output="input+1.0"')
Flow('synth-noisy-xy-t','synth-noisy-xy','math output="input+1.0"')
Flow('synth-obs-xy-t','synth-obs-xy','math output="input+1.0"')
Flow('synth-hooi-xy-t','synth-hooi-xy','math output="input+1.0"')
Flow('synth-drr-xy-t','synth-drr-xy','math output="input+1.0"')
Flow('synth-mrc-xy-t','synth-mrc-xy','math output="input+1.0"')

Flow('synth-original-hxhy-t','synth-original-hxhy','math output="input+1.0"')
Flow('synth-noisy-hxhy-t','synth-noisy-hxhy','math output="input+1.0"')
Flow('synth-obs-hxhy-t','synth-obs-hxhy','math output="input+1.0"')
Flow('synth-hooi-hxhy-t','synth-hooi-hxhy','math output="input+1.0"')
Flow('synth-drr-hxhy-t','synth-drr-hxhy','math output="input+1.0"')
Flow('synth-mrc-hxhy-t','synth-mrc-hxhy','math output="input+1.0"')

Flow('synth-noisy-xy-simi','synth-original-xy synth-noisy-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-obs-xy-simi','synth-original-xy synth-obs-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-hooi-xy-simi','synth-original-xy synth-hooi-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-drr-xy-simi','synth-original-xy synth-drr-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-mrc-xy-simi','synth-original-xy synth-mrc-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')

End()
