from rsf.proj import *
# PLEASE NOTE:
# The sffxynpre2 is sometimes unstable (for large datasets with windowed processing; it works fine for smaller datasets) due to some unknown memory allocation error
# We have been debugging the errors for a long time but still haven't fixed the issue
# But, generally, it is only an implementation problem (in C) and does not affect the final result. 
# If the error shows up, please keep using "scons lock" (many times) to continue where it was stopped. Although it is not automatic, and is a little bit stupid, it solves the problem (to some extent) and outputs the result shown in our paper.
# We are asking interested researchers to dig into the codes (RSFSRC/user/chenyk/fxynpre.c and related subroutines) and to find the bug that causes the memory issue.
# If you have found the issue/bug, please contact me at chenyk2016@@gmail.com. Thank you! 
# 
# datapath: https://drive.google.com/file/d/1tXcH1aW7lmulq9x8g07AebgEtysV8EaP/view?usp=sharing 

def Grey3(data1,data,other):
	Result(data1,data,
       '''
       window f3=48|byte gainpanal=e clip=2 |
       grey3 flat=n frame1=250 frame2=50 frame3=100 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title= color=g
       screenratio=1.2 %s'''%other)

def Grey31(data1,data,other):
	Result(data1,data,
       '''
       byte gainpanal=e clip=2 |
       grey3 flat=n frame1=250 frame2=50 frame3=100 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title= color=g
       screenratio=1.2 %s'''%other)
              
def Grey3r(data1,data,other):
	Result(data1,data,
       '''
       byte gainpanal=e clip=20 allpos=y bar=bar.rsf|put d1=1 d2=1 d3=1|
       grey3 flat=n frame1=250 frame2=32 frame3=16 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time sampling number" unit1= title= color=g
       screenratio=1.2 %s'''%other)
       
def Grey3s(data,other):
	Result(data,
       '''
       window f3=48|byte allpos=y clip=0.8 bar=bar.rsf|
       grey3 flat=n frame1=250 frame2=60 frame3=50 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title=  scalebar=y screenratio=1.2 maxval=0.5 minval=0 %s'''%other)

def Grey3s1(data,other):
	Result(data,
       '''
       byte allpos=y clip=0.8 bar=bar.rsf|
       grey3 flat=n frame1=250 frame2=60 frame3=50
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title=  scalebar=y screenratio=1.2 maxval=0.5 minval=0 %s'''%other)

### prepare the real 3D seismic data
Flow('data','data3d.rsf','cp')
Grey3('real','data','title="Raw data"')

### windowed function
Flow('test0','data','fxynpre n1win=256 n2win=64 n3win=32 mode=0 fs=0 nsx=3 nsy=3 rect1=4 rect2=3 rect3=2 niter=20 verb=y')
Flow('test0-n','test0 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest0','test0','title="NPF"')
Grey3('rtest0-n','test0-n','title="NPF"')

Flow('test00','data','fxynpre n1win=256 n2win=64 n3win=32 mode=0 fs=1 nsx=3 nsy=3 rect1=4 rect2=3 rect3=2 niter=20 verb=y')
Flow('test00-n','test00 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest00','test00','title="NPFFS"')
Grey3('rtest00-n','test00-n','title="NPFFS"')

#Flow('test1','data','fxynpre n1win=256 n2win=64 n3win=32 mode=1 nsx=3 nsy=3 rect2=3 rect3=2 niter=20 verb=y')
Flow('test1','data','fxynpre n1win=256 n2win=64 n3win=32 mode=1 nsx=2 nsy=2 rect2=4 rect3=4 niter=20 verb=y')
Flow('test1-n','test1 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest1','test1','title="RNAR"')
Grey3('rtest1-n','test1-n','title="RNAR"')

# Flow('test2','data','fxynpre n1win=256 n2win=64 n3win=32 mode=2 nsx=3 nsy=3 rect2=3 rect3=2 niter=20 verb=y')
# Flow('test2','data','fxynpre n1win=256 n2win=64 n3win=32 mode=2 nsx=2 nsy=2 rect2=3 rect3=2 niter=20 verb=y')
Flow('test2','data','fxynpre n1win=512 n2win=128 n3win=64 mode=2 nsx=2 nsy=2 rect2=3 rect3=2 niter=20 verb=y')
Flow('test2-n','test2 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest2','test2','title="SPF"')
Grey3('rtest2-n-0','test2-n','title="SPF"')


Plot('labelspf0',None,
	'''
	box x0=2.2 y0=4.6 label="" xt=0.5 yt=-0.5 length=0.5 
	''')
Plot('labelspf1',None,
	'''
	box x0=3 y0=4.8 label="" xt=0.5 yt=-0.5 length=0.5 
	''')	
Result('rtest2-n','Fig/rtest2-n-0.vpl labelspf0 labelspf1','Overlay')

########## Patch (fxynpre2 not easy for inside patching)
Flow('patch','data','patch w=256,64,32 p=5,3,15')
Flow('patch0','patch','patch inv=y weight=y dim=3')

#Result('patch','patch','grey title="Patch Data"')
#Result('patch0','patch0','grey title=" Inv Patch Data"')

wflts = []
wpres = []
wpreis=[]
rx_max=6 
rx_ref=3
ry_max=6 
ry_ref=3
rf_max=6 
rf_ref=3
for nwt in range(0,225):
    wdata  = 'wdata%d'  % nwt
    wflt   = 'wfl%d'    % nwt
    wprei   = 'wprei%d'    % nwt
    wpre   = 'wpre%d'    % nwt
    rect1   = 'rect1-%d'    % nwt
    rect2   = 'rect2-%d'    % nwt
    rect3   = 'rect3-%d'    % nwt
    Flow(wdata,'patch','put n4=225 n5=1 n6=1|window n4=1 f4=%d ' % nwt) 
    Flow(wprei,wdata,'fxynpre mode=0  nsx=3 nsy=3 rect1=4 rect2=3 rect3=2 niter=20 verb=y')
#     Flow(rect1,wprei,'fft1|cabs|math output="input*input"|scale axis=2|mask min=0.001 | dd type=float|math output="-%g*input+%g"'%(rf_max-rf_ref,rf_max))
#     Flow(rect2,wprei,'fft1|cabs|math output="input*input"|scale axis=2|mask min=0.001 | dd type=float|math output="-%g*input+%g"'%(rx_max-rx_ref,rx_max))
#     Flow(rect3,wprei,'fft1|cabs|math output="input*input"|scale axis=2|mask min=0.001 | dd type=float|math output="-%g*input+%g"'%(ry_max-ry_ref,ry_max))
    Flow(rect1,wprei,'fft1|cabs|math output="input*input"|scale axis=2 | dd type=float|math output="-%g*input+%g"'%(rf_max-rf_ref,rf_max))
    Flow(rect2,wprei,'fft1|cabs|math output="input*input"|scale axis=2 | dd type=float|math output="-%g*input+%g"'%(rx_max-rx_ref,rx_max))
    Flow(rect3,wprei,'fft1|cabs|math output="input*input"|scale axis=2 | dd type=float|math output="-%g*input+%g"'%(ry_max-ry_ref,ry_max))
#     Flow(rect1,wprei,'fft1|cabs|math output="input*input"|scale axis=2 | dd type=float|math output="%g*input+%g"'%(rf_max-rf_ref,rf_ref))
#     Flow(rect2,wprei,'fft1|cabs|math output="input*input"|scale axis=2 | dd type=float|math output="%g*input+%g"'%(rx_max-rx_ref,rx_ref))
#     Flow(rect3,wprei,'fft1|cabs|math output="input*input"|scale axis=2 | dd type=float|math output="%g*input+%g"'%(ry_max-ry_ref,ry_ref))
    Grey3r(rect1,rect1,'color=j allpos=y scalebar=y')

    Flow(wpre,[wdata,rect1,rect2,rect3],'fxynpre2 mode=3 nsx=3 nsy=3  rect1=${SOURCES[1]} rect2=${SOURCES[2]} rect3=${SOURCES[3]} niter=20 verb=y')
    wpres.append(wpre)
    wpreis.append(wprei)

Flow('pre',wpres,'cat ${SOURCES[1:%d]} axis=4 ' % len(wpres))
Flow('prei',wpreis,'cat ${SOURCES[1:%d]} axis=4 ' % len(wpres))
Flow('test3','pre','put n4=5 n5=3 n6=15| patch inv=y weight=y dim=3|window f3=48')
Flow('test3-n','data test3','window f3=48|add scale=1,-1 ${SOURCES[1]}')
Flow('test0-patch','prei','put n4=5 n5=3 n6=15| patch inv=y weight=y dim=3')
Flow('test0-patch-n','data test0-patch','add scale=1,-1 ${SOURCES[1]}')

Grey31('rtest3','test3','title="NPFFXS"')
Grey31('rtest3-n','test3-n','title="NPFFXS"')
Grey3('rtest0-patch','test0-patch','title="NPF"')
Grey3('rtest0-patch-n','test0-patch-n','title="NPF"')

#local similarity
Flow('rsimi0','test0 test0-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi00','test00 test00-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi1','test1 test1-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi2','test2 test2-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi3','test3 test3-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')

Grey3s('rsimi0','color=j title="NPF"')
Grey3s('rsimi00','color=j title="NPFFS"')
Grey3s('rsimi1','color=j title=RNAR')
Grey3s('rsimi2','color=j title=SPF')
Grey3s1('rsimi3','color=j title="NPFFXS"')

##zooming
Flow('real-z','data','window f3=48 | window min1=0.75 n1=100 f2=32 n2=64 n3=100')
Flow('rtest0-z','test0','window f3=48 | window min1=0.75 n1=100 f2=32 n2=64 n3=100')
Flow('rtest00-z','test00','window f3=48 | window min1=0.75 n1=100 f2=32 n2=64 n3=100')
Flow('rtest00dif-z','rtest0-z rtest00-z','add scale=1,-1 ${SOURCES[1]}')
Flow('rtest3dif-z','rtest00-z rtest3-z','add scale=1,-1 ${SOURCES[1]}')
Flow('rtest1-z','test1','window f3=48 | window min1=0.75 n1=100 f2=32 n2=64 n3=100')
Flow('rtest2-z','test2','window f3=48 | window min1=0.75 n1=100 f2=32 n2=64 n3=100')
Flow('rtest3-z','test3','window min1=0.75 n1=100 f2=32 n2=64 n3=100')
Grey31('real-z-0','real-z','screenratio=0.6 title="Raw data"')
Grey31('rtest0-z-0','rtest0-z','screenratio=0.6 title="NPF"')
Grey31('rtest00-z-0','rtest00-z','screenratio=0.6 title="NPFFS"')
Grey31('rtest00dif-z-0','rtest00dif-z','screenratio=0.6 title="Difference"')
Grey31('rtest3dif-z-0','rtest3dif-z','screenratio=0.6 title="Difference"')
Grey31('rtest1-z-0','rtest1-z','screenratio=0.6 title="RNAR"')
Grey31('rtest2-z-0','rtest2-z','screenratio=0.6 title="SPF"')
Grey31('rtest3-z-0','rtest3-z','screenratio=0.6 title="NPFFXS"')


Plot('label1',None,
	'''
	box x0=4 y0=6.4 label="" xt=0.5 yt=-0.5 length=0.5 
	''')
Plot('label2',None,
	'''
	box x0=6 y0=4.8 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('label3',None,
	'''
	box x0=9 y0=4.8 label="" xt=0.5 yt=0.5 length=0.5 
	''')
Plot('label4',None,
	'''
	box x0=12 y0=6.8 label="" xt=-0.5 yt=-0.5 length=0.5 
	''')
Result('real-z','Fig/real-z-0.vpl label1 label2 label3 label4','Overlay')
Result('rtest1-z','Fig/rtest1-z-0.vpl label1 label2 label3 label4','Overlay')
Result('rtest2-z','Fig/rtest2-z-0.vpl label1 label2 label3 label4','Overlay')
Result('rtest3-z','Fig/rtest3-z-0.vpl label1 label2 label3 label4','Overlay')
Result('rtest0-z','Fig/rtest0-z-0.vpl label1 label2 label3 label4','Overlay')
Result('rtest00-z','Fig/rtest00-z-0.vpl label1 label2 label3 label4','Overlay')






End()

