from rsf.proj import *
# 
# Google: https://drive.google.com/file/d/1naNHe4gKSAXVpAcXGt_wZQF50OVXvL-b/view?usp=sharing
# Baidu:
# 

Flow('chev','chev.bin',
     '''
     bin2rsf bfile=${SOURCES[0]} n1=34 n2=202500 o1=0.4020 d1=0.006 o2=1 d2=1
     |put n2=450 n3=450|
     put o2=7923.3979 d2=12.5 o3=10298.643 d3=12.5
     label1=Time unit1=s label2=Inline unit2=m label3=Crossline unit3=m |
     scale dscale=0.01
     ''')   

Flow('spec','chev','pad n1=256 | spectra all=y')

def cubeplot(title,clip='',extra=''):
    return '''
    window n1=34 min1=0.402 |
    byte gainpanel=all %s |
    transp plane=13 |
    grey3 frame3=18 frame2=350 frame1=250 flat=y point1=0.8 point2=0.8
    label3=Time unit3=s label2=Inline unit2=m label1=Crossline unit1=m
    title="%s" %s screenratio=1 labelsz=5 labelsz=8 titlesz=8 titlefat=2 labelfat=2 font=2
    ''' % (clip,title,extra)

def Cubeplot(name,frame=18):
    t=0.402+0.006*frame
    Plot(name+'0',name,
         '''
         window n1=1 f1=%g | transp | grey label2=Inline unit2=m label1=Crossline unit1=m wanttitle=n
         grid=y g1num0=12298.4 g1num=10000 g2num0=13423.6 g2num=10000 gridcol=6 gridfat=5 labelsz=5
         screenratio=1 scalebar=y barlabel=Amplitude parallel2=n
         ''' % frame)
    
    Plot(name+'1',name,
         '''
         window n3=1 f3=250 | grey label2= unit2= label1=Time unit1=s labelsz=5
         grid=y g1num0=12298.4 g1num=10000 g2num0=%g g2num=10000 gridcol=6 gridfat=5 screenratio=1
         scalebar=y barlabel=Amplitude parallel2=n format2="%%3.1f" o2num=0.4 d2num=0.1 formatbar="%%g"
         title="Inline (m)" titlesz=5 wheretitle=t dbarnum=1 nbartic=10
         ''' % t)
    Plot(name+'2',name,
         '''
         window n2=1 f2=350 | grey label2= unit2= label1=Time unit1=s labelsz=5
         grid=y g1num0=13423.6 g1num=10000 g2num0=%g g2num=10000 gridcol=6 gridfat=5 screenratio=1
         scalebar=y barlabel=Amplitude parallel2=n format2="%%3.1f" o2num=0.4 d2num=0.1 formatbar="%%g"
         title="Crossline (m)" titlesz=5 wheretitle=t dbarnum=1 nbartic=10
         ''' % t)
    Plot(name+'12',[name+'1',name+'2'],'OverUnderAniso',vppen='txscale=2')
    Result(name,[name+'0',name+'12'],'OverUnderIso')

#Result('chev',cubeplot(' '))

Cubeplot('chev')

Plot('chev',cubeplot(' '))

patch = 'patch w=84,250,250 p=1,2,2 | put n4=1 n5=4 n6=1'

Flow('chev-pad','chev','pad beg1=25 end1=25')
Flow('patch','chev-pad',patch)
Flow('mask','chev','math output=1 | pad beg1=25 end1=25 |' + patch)

## uncomment the following since it takes most of time
Flow('dip','patch mask','dip rect1=10 rect2=10 rect3=10 mask=${SOURCES[1]}',
     split=[5,4,[0,1]])
Flow('dipx','dip','window n4=1 | put n4=1 n5=2 n6=2 | patch inv=y weight=y')
Flow('dipy','dip','window f4=1 | put n4=1 n5=2 n6=2 | patch inv=y weight=y')
Flow('dips','dipx dipy','cat axis=4 ${SOURCES[1]}')

Result('dipx',
       cubeplot('Inline Dip','bar=bar1.rsf',
                '''
                color=j scalebar=y bar=bar1.rsf wanttitle=n
                barlabel="Inline Dip" bartype=h
                '''))
Result('dipy',
       cubeplot('Crossline Dip','bar=bar2.rsf',
                '''
                color=j scalebar=y bar=bar2.rsf wanttitle=n
                barlabel="Crossline Dip" bartype=h
                '''))

Flow('shift1','chev','window f2=1')
Flow('shift2','chev','window f3=1')

Flow('last1','chev','window f2=449 squeeze=n')
Flow('last2','chev','window f3=449  squeeze=n')

Flow('ref1','shift1 last1','cat axis=2 ${SOURCES[1]}')
Flow('ref2','shift2 last2','cat axis=3 ${SOURCES[1]}')

Flow('ref1s','ref1','add mode=p $SOURCE | stack axis=1 norm=n')
Flow('ref2s','ref2','add mode=p $SOURCE | stack axis=1 norm=n')

Flow('corr1','ref1 chev','add mode=p ${SOURCES[1]} | stack axis=1 norm=n')
Flow('corr2','ref2 chev','add mode=p ${SOURCES[1]} | stack axis=1 norm=n')

Flow('chev2','chev','add mode=p $SOURCE | stack axis=1 norm=n')

Flow('cos1','corr1 chev2 ref1s',
     '''
     math s1=${SOURCES[1]} s2=${SOURCES[2]} output="(s1*s2)/(input*input)"
     ''')
Flow('cos2','corr2 chev2 ref2s',
     '''
     math s1=${SOURCES[1]} s2=${SOURCES[2]} output="(s1*s2)/(input*input)"
     ''')
Flow('cos','cos1 cos2',
     'cat axis=3 ${SOURCES[1]} ')

Plot('cos1',
     '''
     grey color=j scalebar=y bartype=v allpos=y bias=1 
     title="West-East Cost" transp=n yreverse=n
     ''')
Plot('cos2',
     '''
     grey color=j scalebar=y bartype=v allpos=y bias=1
     title="South-North Cost" transp=n yreverse=n
     ''')
Result('chos','cos1 cos2','SideBySideIso')

Flow('seed','dips','window n2=1 n3=1 n4=1 | math output=x1')
Flow('pick','dips seed cos',
     '''
     pwpaint3 seed=${SOURCES[1]} cost=${SOURCES[2]} ref2=250 ref3=350 | 
     bandpass fhi=40
     ''')

Result('pick',cubeplot('','allpos=y','color=j wanttitle=n'))

Flow('flat','chev-pad pick','iwarp warp=${SOURCES[1]} eps=1 n1=34 o1=0.402')
Result('flat',cubeplot(''))


# multiple references

picks = []
for ref in ((150,150),(300,150),(300,300)):
        pick = 'pick%d-%d' % ref
        picks.append(pick)

        Flow(pick,'dips seed cos',
             '''
             pwpaint3 seed=${SOURCES[1]} cost=${SOURCES[2]} ref2=%d ref3=%d | 
             bandpass fhi=40
             ''' % ref)        

np = len(picks)
Flow('picks',picks,
     'add ${SOURCES[1:%d]} | scale dscale=%g' % (np,1.0/np))

Flow('flats','chev-pad picks','iwarp warp=${SOURCES[1]} eps=1 n1=34 o1=0.402')
#Result('flats',cubeplot('') + ' frame3=20')

Cubeplot('flats',frame=20)

Flow('spec-flat','flats','pad n1=256 | spectra all=y')

Result('spec','spec spec-flat','cat axis=2 ${SOURCES[1]} | scale axis=1 | graph dash=1,0 title=Spectrum label2= unit2=')

Flow('timefreq','flats','timefreq rect=5 nw=12 dw=5')

Flow('tf_ltft','flats','ltft rect=5 nw=12 dw=5')

Flow('rect0','flats','spray axis=2 n=24 d=5 o=0 |math output="1"')#smooth in frequency
Flow('rect1','flats','spray axis=2 n=24 d=5 o=0 |math output="5"')#smooth in time
Flow('rect2','flats','spray axis=2 n=24 d=5 o=0 |math output="5"')#smooth in x
Flow('rect3','flats','spray axis=2 n=24 d=5 o=0 |math output="5"')#smooth in y


Flow('tf_ltftn','flats rect0 rect1 rect2 rect3','ltftn rect=5 nw=12 dw=5 rect0=${SOURCES[1]} rect1=${SOURCES[2]} rect2=${SOURCES[3]} rect3=${SOURCES[4]} | transp plane=34|transp plane=23')

Result('slice','flats','window n1=1 f1=20 | grey transp=n title=Amplitude unit1=m unit2=m screenratio=1 scalebar=y parallel2=n labelsz=6')




# ## Create non-stationary smoothing radius
r_ref=3 #reference radius
r_max=5 #reference radius
Flow('chev_ltft_se','tf_ltft','cabs')#energy
Flow('chev_rect-n0','chev_ltft_se','math output="input*input"|scale axis=2|mask min=0.8|dd type=float|math output="-%g*input+%g"'%(1-1,1))
Flow('chev_rect-n1','chev_ltft_se','math output="input*input"|scale axis=2|mask min=0.8|dd type=float|math output="-%g*input+%g"'%(r_max-r_ref,r_max))
Flow('chev_rect-n2','chev_ltft_se','math output="input*input"|scale axis=2|mask min=0.8|dd type=float|math output="-%g*input+%g"'%(r_max-r_ref,r_max))
Flow('chev_rect-n3','chev_ltft_se','math output="input*input"|scale axis=2|mask min=0.8|dd type=float|math output="-%g*input+%g"'%(r_max-r_ref,r_max))


Flow('rect00','chev_rect-n0','cat axis=2 ${SOURCES[0]}')
Flow('rect11','chev_rect-n1','cat axis=2 ${SOURCES[0]}')
Flow('rect22','chev_rect-n2','cat axis=2 ${SOURCES[0]}')
Flow('rect33','chev_rect-n3','cat axis=2 ${SOURCES[0]}')

Result('chev_ltft_se',
           'window n1=1 f1=20 n2=1 min2=%d | grey title="%g Hz" transp=n unit1=m unit2=m allpos=y scalebar=y parallel2=n labelsz=6 screenratio=1 pclip=99 color=j' % (25,25))

Result('chev_rect-n1',
           'window n1=1 f1=20 n2=1 min2=%d | grey title="%g Hz" transp=n unit1=m unit2=m allpos=y scalebar=y parallel2=n labelsz=6 screenratio=1 pclip=99 color=j' % (25,25))

Flow('tf_ltftn2','flats rect00 rect11 rect22 rect33','ltftn rect=5 nw=12 dw=5 rect0=${SOURCES[1]} rect1=${SOURCES[2]} rect2=${SOURCES[3]} rect3=${SOURCES[4]} | transp plane=34|transp plane=23')


for freq in (10,15,20,25,30,35,40,45,50):
    slice = 'slice%d' % freq
    Result(slice,'timefreq',
           'window n1=1 f1=20 n2=1 min2=%d | grey labelsz=8 titlesz=8 titlefat=2 labelfat=2 font=2 title="%g Hz" transp=n unit1=m unit2=m allpos=y  screenratio=1 pclip=95 color=j' % (freq,freq))

for freq in (10,15,20,25,30,35,40,45,50):
    slice = 'ltft-slice%d' % freq
    Result(slice,'tf_ltft',
           'cabs|put o3=7923.4 o4=10298.6 d3=12.5 d4=12.5|window n1=1 f1=20 n2=1 min2=%d | grey labelsz=8 titlesz=8 titlefat=2 labelfat=2 font=2 title="%g Hz" transp=n unit1=m unit2=m allpos=y  screenratio=1 pclip=95 color=j' % (freq,freq))

for freq in (10,15,20,25,30,35,40,45,50):
    slice = 'ltftn-slice%d' % freq
    Result(slice,'tf_ltftn',
           'cabs|put o3=7923.4 o4=10298.6 d3=12.5 d4=12.5|window n1=1 f1=20 n2=1 min2=%d |grey labelsz=8 titlesz=8 titlefat=2 labelfat=2 font=2 title="%g Hz" transp=n unit1=m unit2=m allpos=y  screenratio=1 pclip=95 color=j' % (freq,freq))

for freq in (10,15,20,25,30,35,40,45,50):
    slice = 'ltftn2-slice%d' % freq
    Result(slice,'tf_ltftn2',
           'cabs|put o3=7923.4 o4=10298.6 d3=12.5 d4=12.5|window n1=1 f1=20 n2=1 min2=%d  | grey labelsz=8 titlesz=8 titlefat=2 labelfat=2 font=2 title="%g Hz" transp=n unit1=m unit2=m allpos=y  screenratio=1 pclip=95 color=j' % (freq,freq))


Flow('den','timefreq','stack')
Flow('num','timefreq','math output="x2*input" | stack')

Flow('freq','num den','div ${SOURCES[1]}')

Result('freq','window n1=1 f1=20 | grey color=j scalebar=y title="Dominant Frequency" bias=15 allpos=y barlabel=Frequency barunit=Hz')




Plot('label1',None,
	'''
	box x0=3.0 y0=3.4 label="" xt=0.5 yt=0.5 length=1 
	''')
Plot('label2',None,
	'''
	box x0=3.0 y0=4.4 label="" xt=0.5 yt=0.5 length=1 
	''')
Plot('label3',None,
	'''
	box x0=3.0 y0=5.4 label="" xt=0.5 yt=0.5 length=1 
	''')
Plot('label3C',None,
	'''
	box x0=3.0 y0=5.4 label="Channel" xt=0.5 yt=0.5 length=1 
	''')
Plot('label4',None,
	'''
	box x0=2.1 y0=5.6 label="" xt=0.5 yt=0.5 length=0.7 
	''')
Plot('label5',None,
	'''
	box x0=2.1 y0=6.4 label="" xt=0.5 yt=0.5 length=1 
	''')
Plot('label5C',None,
	'''
	box x0=2.1 y0=6.4 label="Channel" xt=0.5 yt=0.5 length=1 
	''')
Plot('label55',None,
	'''
	box x0=3.1 y0=6.4 label="" xt=0.5 yt=0.5 length=1 
	''')
Plot('label6',None,
	'''
	box x0=2.8 y0=7.8 label="" xt=-0.5 yt=0.5 length=1 
	''')	

Result('ltft-slice25-0','Fig/ltft-slice25.vpl label1 label2 label3 label3 label4 label5 label55 label6','Overlay')
Result('ltft-slice30-0','Fig/ltft-slice30.vpl label1 label2 label3 label3 label4 label5 label55 label6','Overlay')
Result('ltft-slice35-0','Fig/ltft-slice35.vpl label1 label2 label3 label3 label4 label5 label55 label6','Overlay')
Result('ltft-slice40-0','Fig/ltft-slice40.vpl label1 label2 label3 label3 label4 label5 label55 label6','Overlay')
Result('ltft-slice45-0','Fig/ltft-slice45.vpl label1 label2 label3 label3 label4 label5 label55 label6','Overlay')
Result('ltft-slice50-0','Fig/ltft-slice50.vpl label1 label2 label3 label3 label4 label5 label55 label6','Overlay')

Result('ltftn-slice25-0','Fig/ltftn-slice25.vpl label1 label2 label3 label3C label4 label5C label55 label6','Overlay')
Result('ltftn-slice30-0','Fig/ltftn-slice30.vpl label1 label2 label3 label3C label4 label5C label55 label6','Overlay')
Result('ltftn-slice35-0','Fig/ltftn-slice35.vpl label1 label2 label3 label3C label4 label5C label55 label6','Overlay')
Result('ltftn-slice40-0','Fig/ltftn-slice40.vpl label1 label2 label3 label3C label4 label5C label55 label6','Overlay')
Result('ltftn-slice45-0','Fig/ltftn-slice45.vpl label1 label2 label3 label3C label4 label5C label55 label6','Overlay')
Result('ltftn-slice50-0','Fig/ltftn-slice50.vpl label1 label2 label3 label3C label4 label5C label55 label6','Overlay')

# ltft-slice25,ltftn-slice25,ltft-slice30,ltftn-slice30,ltft-slice35,ltftn-slice35


End()
