from rsf.tex import*
os.environ['PSTEXPENOPTS']='color=y fat=3 fatmult=1.5'

## add pdflatex into default PATH
import sys
env=Environment()
if sys.platform == 'darwin':
    env['ENV']['PATH'] = ':'.join(['/opt/local/bin',env['ENV']['PATH']])


Paper('sswteage',lclass='mad15',use='listings, amsmath,subfigure')
Paper('sswt',options='manuscript',use='listings, amsmath,subfigure')


Paper('sswt',options='manuscript',use='listings, amsmath,subfigure')
Paper('sswt_revise1',lclass='geophysics',options='manuscript,revised',use='amsmath')
Command('sswt_revise_plain1.tex','sswt_revise1.tex','cp $SOURCE $TARGET')
Paper('sswt_revise_plain1',lclass='geophysics',options='manuscript',use='subfigure,natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')


Paper('sswt_jge',lclass='geophysics',options='manuscript',use='subfigure,natbib,amsmath,graphicx,color,lineno',
          include=r'''
          \linenumbers*[1]
          ''')
#Paper('sswt',use='listings, amsmath,subfigure')

Paper('seg2015_sswt',lclass='segabs',use='listings, amsmath,subfigure')
env.Command('seg2015_sswt_final.pdf','seg2015_sswt_final.ltx','pdflatex $SOURCE')

Paper('reply1',use='hyperref,listings')
Paper('reply2',use='hyperref,listings')

Paper('slides-sswt',lclass='beamer',use='subfigure,amsmath,amsbsy,listings,overpic,color,multicol,amssymb,comment,verbatim', include=r'''
      \mode<presentation>{\usetheme{beaver}}
      \mode<presentation>{\usecolortheme{beaver}}
      \newcommand{\TEXMF}{%s/texmf}
      ''' % os.environ.get('HOME'))

Paper('ieee_karst',lclass='IEEEtran',options='10pt',use='graphicx,subfigure,amsmath')

#Paper('int_karst','manuscript',use='subfigure,natbib,amsmath,graphicx,color,lineno',
#          include=r'''
#          \linenumbers*[1]
#          ''')
Paper('int_r1',options='manuscript,revised',use='subfigure,morefloats,natbib,amsmath')
Command('int_plain1.tex','int_r1.tex','cp $SOURCE $TARGET')
Paper('int_plain1',options='manuscript',use='subfigure,natbib,amsmath')

Paper('int_r2',options='manuscript,revised',use='subfigure,morefloats,natbib,amsmath')
Command('int_plain2.tex','int_r2.tex','cp $SOURCE $TARGET')
Paper('int_plain2',options='manuscript',use='subfigure,natbib,amsmath')


          
End(use='listings,amsmath')
