from rsf.proj import *
import math


nt=501
dt = 0.008
nf = 300
ot=0
df = 1/(nt*dt)
wf = 2*math.pi

def Grey(data,other):
	Result(data,'grey grid=n labelsz=8 titlesz=8 titlefat=1 labelfat=1 font=2 label2=Trace  unit2="" label1=Time unit1="s" title="" wherexlabel=b scalebar=n wheretitle=t clip=0.4 screenratio=1.2 %s'%other)

def Greyr(data,other):
	Result(data,
	'''
	  window n1=501 |
       grey transp=n yreverse=n color=j
       crowd1=0.75 crowd2=0.25 labelsz=8 titlesz=8 titlefat=1 labelfat=1 font=2
       labelfat=1 font=2 titlefat=1 parallel2=n wanttitle=n %s'''%(other))

def Greyf(data,other):
	Result(data,
	   '''
	   window n1=501 |
       cabs|
       grey transp=n yreverse=n color=j
       crowd1=0.75 crowd2=0.25 labelsz=8 titlesz=8 titlefat=1 labelfat=1 font=2
       labelfat=1 font=2 titlefat=1 parallel2=n %s'''%(other))

def Graph(data,other):
	Result(data,'graph grid=n label2=Amplitude  unit2="" labelsz=8 titlesz=8 titlefat=1 labelfat=1 font=2 label1=Time unit1="s" title="" wherexlabel=b scalebar=n wheretitle=t  title=Input labelfat=1 font=2 titlefat=1 crowd1=0.75 crowd2=0.25 parallel2=n wherexlabel=t wheretitle=b plotfat=1 %s'%other)

def Grey3(data,other):
	Result(data,'cabs|byte allpos=y clip=0.01 | grey3 flat=n color=j frame2=50 frame1=120 frame3=15 grid=n label1=Time  unit1="s" label3=Trace label2=Frequency unit2="Hz"  unit3= title="" wherexlabel=b scalebar=n wheretitle=t labelsz=8 titlesz=8 titlefat=1 labelfat=1 font=2 screenratio=1.2 point1=0.8 point2=0.8 %s'%other)
	
###########################
# Model 1 crossing chirps
###########################
Flow('cchirpsc',None,
     '''
     spike n1=%d d1=1 o1=0 |
     math output="cos(%g*(10+x1/7)*x1/%d)+cos(%g*(%d/2.8-x1/6.0)*x1/%d)" |
     pad end1=11 
     ''' % (nt,2*math.pi,nt,2*math.pi,nt,nt))
     
Flow('cchirps',None,
     '''
     spike n1=%d d1=1 o1=0 |
     math output="cos(%g*(10+x1/7)*x1/%d)+cos(%g*(%d/2.8-x1/6.0)*x1/%d)" |
     pad end1=11| noise var=0.2 seed=201920
     ''' % (nt,2*math.pi,nt,2*math.pi,nt,nt))


# S transform
Flow('st','cchirps','st')

# test sfltft
Flow('ltft_s scbasiss','cchirps','ltfts rect=7 alpha=0 verb=n niter=10 basis=${TARGETS[1]}')

Flow('rect0','cchirps','spray axis=2 n=514 d=1 o=0 | math output=1')#frequency smooth
Flow('rect1','cchirps','spray axis=2 n=514 d=1 o=0 | math output=7')#time smooth

## Create non-stationary smoothing radius
r_ref=7 #reference radius
r_max=14 #reference radius
Flow('ltft_se','ltft_s','cabs')#energy
Flow('rect-n0','ltft_se','math output="input*input"|scale axis=2|mask min=0.05|dd type=float|math output="-%g*input+%g"'%(3-1,3))
Flow('rect-n1','ltft_se','math output="input*input"|scale axis=2|mask min=0.05|dd type=float|math output="-%g*input+%g"'%(r_max-r_ref,r_max))
Grey('ltft_se','color=j scalebar=y clip=0.1')

Flow('rect00','rect-n0','cat axis=2 ${SOURCES[0]}')
Flow('rect11','rect-n1','cat axis=2 ${SOURCES[0]}')

Flow('ltft_n scbasissn','cchirps rect00 rect11','ltftn rect=7 alpha=0 niter=10 verb=n basis=${TARGETS[1]} rect0=${SOURCES[1]} rect1=${SOURCES[2]}')

# choose parameters
Flow('ltft_s2','cchirps','ltfts rect=14 verb=n')

# With frequency smoothing
Flow('rect03','cchirps','spray axis=2 n=514 d=1 o=0 | math output=2')#frequency smooth
Flow('rect13','cchirps','spray axis=2 n=514 d=1 o=0 | math output=7')#time smooth
Flow('rect04','cchirps','spray axis=2 n=514 d=1 o=0 | math output=3')#frequency smooth
Flow('rect14','cchirps','spray axis=2 n=514 d=1 o=0 | math output=7')#time smooth
Flow('ltft_s3 scbasissn3','cchirps rect03 rect13','ltftn rect=7 alpha=0 niter=10 verb=n basis=${TARGETS[1]} rect0=${SOURCES[1]} rect1=${SOURCES[2]}')
Flow('ltft_s4 scbasissn3','cchirps rect03 rect13','ltftn rect=7 alpha=0 niter=10 verb=n basis=${TARGETS[1]} rect0=${SOURCES[1]} rect1=${SOURCES[2]}')

## plot figures
Graph('cchirpsc','title="Clean chirp signal"')
Graph('cchirps','title="Noisy chirp signal"')

Greyr('rect-n1','color=j scalebar=y bias=7 clip=15 barlabel=Radius barunit=Point')
Greyr('rect-n0','color=j scalebar=y bias=1 clip=3 barlabel=Radius barunit=Point')

Greyf('st','title="ST"') 
Greyf('ltft_s','title="Stationary LTFT  (Rt=7, Rf=1)"') 
Greyf('ltft_s2','title="Stationary LTFT (Rt=14, Rf=1)"')
Greyf('ltft_s3','title="Stationary LTFT  (Rt=7, Rf=2)"') 
Greyf('ltft_s4','title="Stationary LTFT  (Rt=7, Rf=3)"')  
Greyf('ltft_n','title="Non-stationary LTFT"') 




End()

