from rsf.proj import*
from rsf.prog import RSFROOT
from math import pi
# Data size: 301*61*61
 
def Grey3(data,other):
	Result(data,
       '''
       byte clip=0.4 |
       grey3 flat=n frame1=50 frame2=5 frame3=0 
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s unit2=trace unit3=trace title=
       screenratio=1.4 color=grey font=104 %s'''%other)

def Grey3e(data,other,clip):
	Result(data,
       '''
       byte clip=%g |
       grey3 flat=n frame1=40 frame2=2 frame3=5 
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s title=
       screenratio=1.4 color=g font=104 %s'''%(clip,other))

def Grey3s(data,other,clip):
	Result(data,
       '''
       byte clip=%g  gainpanel=all  bar=bar.rsf|
       grey3 flat=n frame1=40 frame2=2 frame3=5 
       point1=0.8 point2=0.8 label2=X label3=Y label1="Time" unit1=s title=
       screenratio=1.4 color=j scalebar=y maxval=1 minval=0 %s'''%(clip,other))
       
def Grey(data,other):
	Result(data,
       '''
       grey label2=Trace label1="Time" unit1=s clip=0.9 title=
       screenratio=1.4 color=g %s'''%other)

#def Wig(data,other):
#	Result(data,
#       '''
#       wiggle poly=y transp=y yreverse=y label2=Trace label1="Time" unit1=s clip=0.4 title=
#       screenratio=1.4 color=g %s'''%other)

def Wig(data,other): 
	Result(data,'''
				put d1=0.004 |
				grey color=g color=g transp=y yreverse=y screenratio=1.4
				wanttitle=y flat=n labelfat=4 font=2 titlefat=4				
				label2=Trace unit2="" label1="Time" unit1=s
				title="" wherexlabel=b wheretitle=t poly=y 
				wheretitle=t wherexlabel=b clip=0.4 labelsz=10 color=g %s'''%other)

def Graph(data,other):
	Result(data,'graph label1="Time" label2="Amplitude" unit2= unit1="s" labelsz=10 labelfat=4 font=2 titlesz=10 titlefat=4 title=" Amplitude comparison" wherexlabel=b wheretitle=t screenratio=0.5 %s' %other)
	
## Load data
########################################################################
# INITIALIZATION
########################################################################
matlab         = WhereIs('matlab')
matROOT = '../matfun'
matfun = 'synth_linear_NV02_MT90'
matlabpath = os.environ.get('MATLABPATH',os.path.join(RSFROOT,'lib'))

if not matlab:
   sys.stderr.write('\nCannot find Matlab.\n')
   sys.exit(1)

############################################################
## generate and process synthetic data
############################################################
Flow('synth-clean-0 synth-noisy-0 synth-obs-0 synth-drr-0 synth-rdrr-0',[os.path.join(matROOT,matfun+'.m')],
    '''MATLABPATH=%(matlabpath)s %(matlab)s 
    -nosplash -nojvm -r "addpath %(matROOT)s;%(matfun)s('${TARGETS[0]}','${TARGETS[1]}','${TARGETS[2]}','${TARGETS[3]}','${TARGETS[4]}');quit"
    '''%vars(),stdin=0,stdout=-1)

Flow('synth-clean0290','synth-clean-0',' put n2=11 n3=11 n4=11 n5=11 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-noisy0290','synth-noisy-0','put n2=11 n3=11 n4=11 n5=11 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-obs0290','synth-obs-0','put n2=11 n3=11 n4=11 n5=11 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-drr0290','synth-drr-0','put n2=11 n3=11 n4=11 n5=11 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-rdrr0290','synth-rdrr-0','put n2=11 n3=11 n4=11 n5=11 d1=0.004 d2=1 d3=1 d4=1 d5=1 o1=0 o2=1 o3=1 o4=1 o5=1')
Flow('synth-clean-xy0290','synth-clean0290','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-noisy-xy0290','synth-noisy0290','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-obs-xy0290','synth-obs0290','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-drr-xy0290','synth-drr0290','window n2=1 n3=1 f2=5 f3=5')
Flow('synth-rdrr-xy0290','synth-rdrr0290','window n2=1 n3=1 f2=5 f3=5')

Grey3('synth-clean-xy0290','title=Clean')
Grey3('synth-noisy-xy0290','title=Noisy')
Grey3('synth-obs-xy0290','title=Observed')
Grey3('synth-drr-xy0290','title=DRR')
Grey3('synth-rdrr-xy0290','title=Proposed')

Flow('synth-clean-hxhy0290','synth-clean0290','window n4=1 n5=1 f4=1 f5=1')
Flow('synth-noisy-hxhy0290','synth-noisy0290','window n4=1 n5=1 f4=1 f5=1')
Flow('synth-obs-hxhy0290','synth-obs0290','window n4=1 n5=1 f4=1 f5=1')
Flow('synth-drr-hxhy0290','synth-drr0290','window n4=1 n5=1 f4=1 f5=1')
Flow('synth-rdrr-hxhy0290','synth-rdrr0290','window n4=1 n5=1 f4=1 f5=1')

Grey3('synth-clean-hxhy0290','title=Clean frame1=50 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace')
Grey3('synth-noisy-hxhy0290','title=Noisy frame1=50 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace')
Grey3('synth-obs-hxhy0290','title=Observed frame1=50 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace')
Grey3('synth-drr-hxhy0290','title=DRR frame1=50 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace')
Grey3('synth-rdrr-hxhy0290','title=Proposed frame1=50 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace')

Flow('s-c','synth-clean-hxhy0290','window n2=1 n3=1 f2=4 f3=4')
Flow('s-n','synth-noisy-hxhy0290','window n2=1 n3=1 f2=4 f3=4')
Flow('s-obs','synth-obs-hxhy0290','window n2=1 n3=1 f2=4 f3=4')
Flow('s-drr','synth-drr-hxhy0290','window n2=1 n3=1 f2=4 f3=4')
Flow('s-rdrr','synth-rdrr-hxhy0290','window n2=1 n3=1 f2=4 f3=4')

Flow('synth-ss','s-n s-obs s-drr s-rdrr s-c','cat axis=2 ${SOURCES[1:5]}')
Graph('synth-ss','plotfat=10 plotcol="1,7,2,5,3"')

Flow('synth-drr-xy-e0290','synth-clean-xy0290 synth-drr-xy0290','add scale=1,-1 ${SOURCES[1]}')
Flow('synth-rdrr-xy-e0290','synth-clean-xy0290 synth-rdrr-xy0290','add scale=1,-1 ${SOURCES[1]}')
Grey3e('synth-drr-xy-e0290','title=DRR frame1=50 frame2=5 frame3=0 label1="Time" unit1=s unit2=trace unit3=trace',0.9)
Grey3e('synth-rdrr-xy-e0290','title=Proposed frame1=50 frame2=5 frame3=0 label1="Time" unit1=s unit2=trace unit3=trace',0.9)

Flow('synth-drr-hxhy-e0290','synth-clean-hxhy0290 synth-drr-hxhy0290','add scale=1,-1 ${SOURCES[1]}')
Flow('synth-rdrr-hxhy-e0290','synth-clean-hxhy0290 synth-rdrr-hxhy0290','add scale=1,-1 ${SOURCES[1]}')
Grey3e('synth-drr-hxhy-e0290','title=DRR frame1=50 frame2=5 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace',0.9)
Grey3e('synth-rdrr-hxhy-e0290','title=Proposed frame1=50 frame2=5 frame3=5 label2=HX label3=HY label1="Time" unit1=s unit2=trace unit3=trace',0.9)

Flow('synth-clean-xy-t0290','synth-clean-xy0290','math output="input+1.0"')
Flow('synth-noisy-xy-t0290','synth-noisy-xy0290','math output="input+1.0"')
Flow('synth-obs-xy-t0290','synth-obs-xy0290','math output="input+1.0"')
Flow('synth-drr-xy-t0290','synth-drr-xy0290','math output="input+1.0"')
Flow('synth-rdrr-xy-t0290','synth-rdrr-xy0290','math output="input+1.0"')

Flow('synth-clean-hxhy-t0290','synth-clean-hxhy0290','math output="input+1.0"')
Flow('synth-noisy-hxhy-t0290','synth-noisy-hxhy0290','math output="input+1.0"')
Flow('synth-obs-hxhy-t0290','synth-obs-hxhy0290','math output="input+1.0"')
Flow('synth-drr-hxhy-t0290','synth-drr-hxhy0290','math output="input+1.0"')
Flow('synth-rdrr-hxhy-t0290','synth-rdrr-hxhy0290','math output="input+1.0"')

Flow('synth-noisy-xy-simi','synth-clean-xy synth-noisy-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-obs-xy-simi','synth-clean-xy synth-obs-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-drr-xy-simi','synth-clean-xy synth-drr-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
Flow('synth-rdrr-xy-simi','synth-clean-xy synth-rdrr-xy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')

Flow('synth-clean-hxhy-s0290','synth-clean-hxhy0290','window n3=1 f3=5')
Flow('synth-noisy-hxhy-s0290','synth-noisy-hxhy0290','window n3=1 f3=5')
Flow('synth-obs-hxhy-s0290','synth-obs-hxhy0290','window n3=1 f3=5')
Flow('synth-drr-hxhy-s0290','synth-drr-hxhy0290','window n3=1 f3=5')
Flow('synth-rdrr-hxhy-s0290','synth-rdrr-hxhy0290','window n3=1 f3=5')

Flow('synth-drr-hxhy-s-e0290','synth-drr-hxhy-e0290','window n3=1 f3=5')
Flow('synth-rdrr-hxhy-s-e0290','synth-rdrr-hxhy-e0290','window n3=1 f3=5')
Wig('synth-drr-hxhy-s-e0290','title=DRR')
Wig('synth-rdrr-hxhy-s-e0290','title=Proposed')

Wig('synth-clean-hxhy-s0290','title=Clean')
Wig('synth-noisy-hxhy-s0290','title=Noisy')
Wig('synth-obs-hxhy-s0290','title=Observed')
Wig('synth-drr-hxhy-s0290','title=DRR')
Wig('synth-rdrr-hxhy-s0290','title=Proposed')

Flow('synth-clean-xy-s0290','synth-clean-xy0290','window n2=1 f3=2')
Flow('synth-noisy-xy-s0290','synth-noisy-xy0290','window n2=1 f3=2')
Flow('synth-obs-xy-s0290','synth-obs-xy0290','window n2=1 f3=2')
Flow('synth-drr-xy-s0290','synth-drr-xy0290','window n2=1 f3=2')
Flow('synth-rdrr-xy-s0290','synth-rdrr-xy0290','window n2=1 f3=2')

Wig('synth-clean-xy-s0290','title=Clean')
Wig('synth-noisy-xy-s0290','title=Noisy')
Wig('synth-obs-xy-s0290','title=Observed')
Wig('synth-drr-xy-s0290','title=DRR')
Wig('synth-rdrr-xy-s0290','title=Proposed')

Flow('synth-drr-xy-s-e0290','synth-drr-xy-e0290','window n2=1 f3=2')
Flow('synth-rdrr-xy-s-e0290','synth-rdrr-xy-e0290','window n2=1 f3=2')
Wig('synth-drr-xy-s-e0290','title=DRR')
Wig('synth-rdrr-xy-s-e0290','title=Proposed')


#Grey3s('synth-noisy-xy-simi','title=Noisy',1.0)
#Grey3s('synth-obs-xy-simi','title=Observed',1.0)
#Grey3s('synth-rr-xy-simi','title=Traditional',1.0)
#Grey3s('synth-drr-xy-simi','title=Proposed',1.0) 

#Flow('synth-noisy-hxhy-simi','synth-clean-hxhy synth-noisy-hxhy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
#Flow('synth-obs-hxhy-simi','synth-clean-hxhy synth-obs-hxhy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
#Flow('synth-rr-hxhy-simi','synth-clean-hxhy synth-rr-hxhy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')
#Flow('synth-drr-hxhy-simi','synth-clean-hxhy synth-drr-hxhy','similarity other=${SOURCES[1]} rect1=3 rect2=1 rect3=1')

#Grey3s('synth-noisy-hxhy-simi','title=Noisy',1.0)
#Grey3s('synth-obs-hxhy-simi','title=Observed',1.0)
#Grey3s('synth-drr-hxhy-simi','title=DRR',1.0)
#Grey3s('synth-rdrr-hxhy-simi','title=Proposed',1.0)
End()
