from rsf.proj import *
from rsf.recipes.beg import server
def Grey3(data1,data,other):
	Result(data1,data,
       '''
       byte gainpanal=e clip=2 |put d1=0.004 d2=1 d3=1|
       grey3 flat=n frame1=250 frame2=32 frame3=16 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title= color=g
       screenratio=1.2 %s'''%other)
 
def Grey3s(data,other):
	Result(data,
       '''
       byte allpos=y clip=0.2 bar=bar.rsf|put d1=0.004 d2=1 d3=1|
       grey3 flat=n frame1=250 frame2=32 frame3=16 
       point1=0.8 point2=0.8 label2=Inline label3=Xline label1="Time" unit1=s title=  scalebar=y screenratio=1.2 maxval=0.5 minval=0 %s'''%other)

# Fetch data
#Fetch('image3d.rsf','cup',server)

Flow('data','image3d','dd form=native | put d1=0.004 d2=1 d3=1 | window n1=512 j2=2 n2=128 j3=2 n3=32')
Grey3('real','data','title="Raw data"')



### windowed function
Flow('test0','data','fxynpre n1win=256 n2win=64 n3win=32 mode=0 fs=0 nsx=3 nsy=3 rect1=4 rect2=3 rect3=2 niter=20 verb=y')
Flow('test0-n','test0 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest0','test0','title="NPF"')
Grey3('rtest0-n','test0-n','title="NPF"')

Flow('test00','data','fxynpre n1win=256 n2win=64 n3win=32 mode=0 fs=1 nsx=3 nsy=3 rect1=4 rect2=3 rect3=2 niter=20 verb=y')
Flow('test00-n','test00 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest00','test00','title="NPFFS"')
Grey3('rtest00-n','test00-n','title="NPFFS"')

Flow('test1','data','fxynpre n1win=256 n2win=64 n3win=32 mode=1 nsx=3 nsy=3 rect2=3 rect3=2 niter=20 verb=y')
Flow('test1-n','test1 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest1','test1','title="RNAR"')
Grey3('rtest1-n','test1-n','title="RNAR"')

Flow('test2','data','fxynpre n1win=256 n2win=64 n3win=32 mode=2 nsx=3 nsy=3 rect2=3 rect3=2 niter=20 verb=y')
Flow('test2-n','test2 data','add scale=-1,1 ${SOURCES[1]}')
Grey3('rtest2','test2','title="SPF"')
Grey3('rtest2-n','test2-n','title="SPF"')


#local similarity
Flow('rsimi0','test0 test0-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi00','test00 test00-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi1','test1 test1-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Flow('rsimi2','test2 test2-n','similarity other=${SOURCES[1]} rect1=5 rect2=3 rect3=3')
Grey3s('rsimi0','color=j title="NPF"')
Grey3s('rsimi00','color=j title="NPFFS"')
Grey3s('rsimi1','color=j title="RNAR"')
Grey3s('rsimi2','color=j title="SPF"')


##zooming
Flow('real-z','data','window n1=100 n2=128 n3=32')
Flow('rtest0-z','test0','window n1=100 n2=128 n3=32')
Flow('rtest00-z','test00','window n1=100 n2=128 n3=32')
Flow('rtest00dif-z','rtest0-z rtest00-z','add scale=1,-1 ${SOURCES[1]}')
Flow('rtest1-z','test1','window n1=100 n2=128 n3=32')
Flow('rtest2-z','test2','window n1=100 n2=128 n3=32')
Grey3('real-z','real-z','screenratio=0.6 title="Raw data"')
Grey3('rtest0-z','rtest0-z','screenratio=0.6 title="NPF"')
Grey3('rtest00-z','rtest00-z','screenratio=0.6 title="NPFFS"')
Grey3('rtest00dif-z','rtest00dif-z','screenratio=0.6 title="Difference"')
Grey3('rtest1-z','rtest1-z','screenratio=0.6 title="RNAR"')
Grey3('rtest2-z','rtest2-z','screenratio=0.6 title="SPF"')

End()

